//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fabric.New.Api.Lang {
	/// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DtoLinkText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DtoLinkText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fabric.Api.Meta.Lang.DtoLinkText", typeof(DtoLinkText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links an App to a particular Member..
        /// </summary>
        internal static string AppDefinesMember {
            get {
                return ResourceManager.GetString("AppDefinesMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links a Descriptor to an Artifact that specifies or clarifies a particular aspect of the Factor&apos;s primary Artifact..
        /// </summary>
        internal static string FactorDescriptorRefinesPrimaryWithArtifact {
            get {
                return ResourceManager.GetString("FactorDescriptorRefinesPrimaryWithArtifact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links a Descriptor to an Artifact that specifies or clarifies a particular aspect of the Factor&apos;s related Artifact..
        /// </summary>
        internal static string FactorDescriptorRefinesRelatedWithArtifact {
            get {
                return ResourceManager.GetString("FactorDescriptorRefinesRelatedWithArtifact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links a Descriptor to an Artifact that specifies or clarifies a particular aspect of the DescriptorType&apos;s meaning or purpose..
        /// </summary>
        internal static string FactorDescriptorRefinesTypeWithArtifact {
            get {
                return ResourceManager.GetString("FactorDescriptorRefinesTypeWithArtifact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links a Factor to its primary Artifact, which represents the starting point of the Factor&apos;s directional Artifact relationship..
        /// </summary>
        internal static string FactorUsesPrimaryArtifact {
            get {
                return ResourceManager.GetString("FactorUsesPrimaryArtifact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links a Factor to its related Artifact, which represents the ending point of the Factor&apos;s directional Artifact relationship..
        /// </summary>
        internal static string FactorUsesRelatedArtifact {
            get {
                return ResourceManager.GetString("FactorUsesRelatedArtifact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links a Vector to an Artifact that &apos;labels&apos; its value&apos;s axis..
        /// </summary>
        internal static string FactorVectorUsesAxisArtifact {
            get {
                return ResourceManager.GetString("FactorVectorUsesAxisArtifact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links a Member to the Artifact that it created..
        /// </summary>
        internal static string MemberCreatesArtifact {
            get {
                return ResourceManager.GetString("MemberCreatesArtifact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links a Member to the Factor that it created..
        /// </summary>
        internal static string MemberCreatesFactor {
            get {
                return ResourceManager.GetString("MemberCreatesFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links a Member to the MemberTypeAssign that it created..
        /// </summary>
        internal static string MemberCreatesMemberTypeAssign {
            get {
                return ResourceManager.GetString("MemberCreatesMemberTypeAssign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links a Member to a historical MemberTypeAssign..
        /// </summary>
        internal static string MemberHasHistoricMemberTypeAssign {
            get {
                return ResourceManager.GetString("MemberHasHistoricMemberTypeAssign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links a Member to its active MemberTypeAssign..
        /// </summary>
        internal static string MemberHasMemberTypeAssign {
            get {
                return ResourceManager.GetString("MemberHasMemberTypeAssign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links a User to a particular Member..
        /// </summary>
        internal static string UserDefinesMember {
            get {
                return ResourceManager.GetString("UserDefinesMember", resourceCulture);
            }
        }
    }
}
