//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fabric.New.Api.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DtoPropText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DtoPropText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fabric.New.Api.Lang.DtoPropText", typeof(DtoPropText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A unique title or identifier..
        /// </summary>
        internal static string App_Name {
            get {
                return ResourceManager.GetString("App_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A secondary label or identifier, used to resolve unique-name conflicts..
        /// </summary>
        internal static string Class_Disamb {
            get {
                return ResourceManager.GetString("Class_Disamb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A descriptive name or title..
        /// </summary>
        internal static string Class_Name {
            get {
                return ResourceManager.GetString("Class_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A summary of the !Class&apos;s intended meaning or purpose. This can resolve confusion in cases where a !Class has vague or missing Factors..
        /// </summary>
        internal static string Class_Note {
            get {
                return ResourceManager.GetString("Class_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The disambiguation text for the new Class.  When provided, the disambiguation text permits the use of a non-unique name..
        /// </summary>
        internal static string CreateClass_Disamb {
            get {
                return ResourceManager.GetString("CreateClass_Disamb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the new Class. It must be unique on its own, or be unique in combination with the disambiguation text..
        /// </summary>
        internal static string CreateClass_Name {
            get {
                return ResourceManager.GetString("CreateClass_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A brief description of the new Class. It can be useful for helping others understand the creator&apos;s intended purpose or meaning..
        /// </summary>
        internal static string CreateClass_Note {
            get {
                return ResourceManager.GetString("CreateClass_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifies the Artifact that refines the Factor&apos;s primary Artifact..
        /// </summary>
        internal static string CreateDescriptor_RefinesPrimaryWithArtifactId {
            get {
                return ResourceManager.GetString("CreateDescriptor_RefinesPrimaryWithArtifactId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifies the Artifact that refines the Factor&apos;s related Artifact..
        /// </summary>
        internal static string CreateDescriptor_RefinesRelatedWithArtifactId {
            get {
                return ResourceManager.GetString("CreateDescriptor_RefinesRelatedWithArtifactId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifies the Artifact that refines the new Descriptor&apos;s DescriptorType..
        /// </summary>
        internal static string CreateDescriptor_RefinesTypeWithArtifactId {
            get {
                return ResourceManager.GetString("CreateDescriptor_RefinesTypeWithArtifactId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifies the DescriptorType for the new Descriptor..
        /// </summary>
        internal static string CreateDescriptor_Type {
            get {
                return ResourceManager.GetString("CreateDescriptor_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifies the DirectorAction associated with the Factor&apos;s primary Artifact..
        /// </summary>
        internal static string CreateDirector_PrimaryAction {
            get {
                return ResourceManager.GetString("CreateDirector_PrimaryAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifies the DirectorAction associated with the Factor&apos;s related Artifact..
        /// </summary>
        internal static string CreateDirector_RelatedAction {
            get {
                return ResourceManager.GetString("CreateDirector_RelatedAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifies the DirectorType for the new Director..
        /// </summary>
        internal static string CreateDirector_Type {
            get {
                return ResourceManager.GetString("CreateDirector_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The day value for the new Eventor..
        /// </summary>
        internal static string CreateEventor_Day {
            get {
                return ResourceManager.GetString("CreateEventor_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The hour value for the new Eventor..
        /// </summary>
        internal static string CreateEventor_Hour {
            get {
                return ResourceManager.GetString("CreateEventor_Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minute value for the new Eventor..
        /// </summary>
        internal static string CreateEventor_Minute {
            get {
                return ResourceManager.GetString("CreateEventor_Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The month value for the new Eventor..
        /// </summary>
        internal static string CreateEventor_Month {
            get {
                return ResourceManager.GetString("CreateEventor_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The second value for the new Eventor..
        /// </summary>
        internal static string CreateEventor_Second {
            get {
                return ResourceManager.GetString("CreateEventor_Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifies the EventorType for the new Eventor..
        /// </summary>
        internal static string CreateEventor_Type {
            get {
                return ResourceManager.GetString("CreateEventor_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The year value for the new Eventor..
        /// </summary>
        internal static string CreateEventor_Year {
            get {
                return ResourceManager.GetString("CreateEventor_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifies the FactorAssertion for the new Factor. In cases where the assertion type is unclear or not known, please use the &apos;Undefined&apos; FactorAssertion..
        /// </summary>
        internal static string CreateFactor_AssertionType {
            get {
                return ResourceManager.GetString("CreateFactor_AssertionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        internal static string CreateFactor_Descriptor {
            get {
                return ResourceManager.GetString("CreateFactor_Descriptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        internal static string CreateFactor_Director {
            get {
                return ResourceManager.GetString("CreateFactor_Director", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        internal static string CreateFactor_Eventor {
            get {
                return ResourceManager.GetString("CreateFactor_Eventor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        internal static string CreateFactor_Identor {
            get {
                return ResourceManager.GetString("CreateFactor_Identor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The IsDefining value for the new Factor..
        /// </summary>
        internal static string CreateFactor_IsDefining {
            get {
                return ResourceManager.GetString("CreateFactor_IsDefining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        internal static string CreateFactor_Locator {
            get {
                return ResourceManager.GetString("CreateFactor_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A sentence or short paragraph describing (in a human-readable format) the intended meaning of the new Factor. A descriptive note can help others understand the creator&apos;s intended purpose or meaning for the Factor..
        /// </summary>
        internal static string CreateFactor_Note {
            get {
                return ResourceManager.GetString("CreateFactor_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifies the primary Artifact for the new Factor..
        /// </summary>
        internal static string CreateFactor_UsesPrimaryArtifactId {
            get {
                return ResourceManager.GetString("CreateFactor_UsesPrimaryArtifactId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifies the related Artifact for the new Factor. The related Artifact cannot be the same as the primary Artifact..
        /// </summary>
        internal static string CreateFactor_UsesRelatedArtifactId {
            get {
                return ResourceManager.GetString("CreateFactor_UsesRelatedArtifactId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        internal static string CreateFactor_Vector {
            get {
                return ResourceManager.GetString("CreateFactor_Vector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifies the IdentorType for the new Identor..
        /// </summary>
        internal static string CreateIdentor_Type {
            get {
                return ResourceManager.GetString("CreateIdentor_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text-based value for the new Identor..
        /// </summary>
        internal static string CreateIdentor_Value {
            get {
                return ResourceManager.GetString("CreateIdentor_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The disambiguation text for the new Instance. When provided, the disambiguation text permits the use of a non-unique name..
        /// </summary>
        internal static string CreateInstance_Disamb {
            get {
                return ResourceManager.GetString("CreateInstance_Disamb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the new Instance. It does not need to be unique..
        /// </summary>
        internal static string CreateInstance_Name {
            get {
                return ResourceManager.GetString("CreateInstance_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A brief description of the new Instance.  It can be useful for helping others understand the creator&apos;s intended purpose or meaning..
        /// </summary>
        internal static string CreateInstance_Note {
            get {
                return ResourceManager.GetString("CreateInstance_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifies the LocatorType for the new Locator..
        /// </summary>
        internal static string CreateLocator_Type {
            get {
                return ResourceManager.GetString("CreateLocator_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The X value for the new Locator..
        /// </summary>
        internal static string CreateLocator_ValueX {
            get {
                return ResourceManager.GetString("CreateLocator_ValueX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Y value for the new Locator..
        /// </summary>
        internal static string CreateLocator_ValueY {
            get {
                return ResourceManager.GetString("CreateLocator_ValueY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Z value for the new Locator..
        /// </summary>
        internal static string CreateLocator_ValueZ {
            get {
                return ResourceManager.GetString("CreateLocator_ValueZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        internal static string CreateMember_DefinedByAppId {
            get {
                return ResourceManager.GetString("CreateMember_DefinedByAppId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        internal static string CreateMember_DefinedByUserId {
            get {
                return ResourceManager.GetString("CreateMember_DefinedByUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        internal static string CreateMember_Type {
            get {
                return ResourceManager.GetString("CreateMember_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The complete absolute URL for new Url object. It must include the URL&apos;s protocol (such as &apos;http://&apos;)..
        /// </summary>
        internal static string CreateUrl_FullPath {
            get {
                return ResourceManager.GetString("CreateUrl_FullPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the new Url..
        /// </summary>
        internal static string CreateUrl_Name {
            get {
                return ResourceManager.GetString("CreateUrl_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifies the VectorType for the new Vector..
        /// </summary>
        internal static string CreateVector_Type {
            get {
                return ResourceManager.GetString("CreateVector_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifies the VectorUnit for the new Vector..
        /// </summary>
        internal static string CreateVector_Unit {
            get {
                return ResourceManager.GetString("CreateVector_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifies the VectorUnitPrefix for the new Vector..
        /// </summary>
        internal static string CreateVector_UnitPrefix {
            get {
                return ResourceManager.GetString("CreateVector_UnitPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Artifact which provides meaning for the new Vector..
        /// </summary>
        internal static string CreateVector_UsesAxisArtifactId {
            get {
                return ResourceManager.GetString("CreateVector_UsesAxisArtifactId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value for the new Vector. This value must be within the range specified by the VectorType. Decimal values are not supported; if additional precision is required, use a VectorUnitPrefix such as Milli or Micro..
        /// </summary>
        internal static string CreateVector_Value {
            get {
                return ResourceManager.GetString("CreateVector_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the type of relationship or connection..
        /// </summary>
        internal static string Descriptor_Type {
            get {
                return ResourceManager.GetString("Descriptor_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the action to be performed on the Factor&apos;s primary Artifact..
        /// </summary>
        internal static string Director_PrimaryAction {
            get {
                return ResourceManager.GetString("Director_PrimaryAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the action to be performed on the Factor&apos;s related Artifact..
        /// </summary>
        internal static string Director_RelatedAction {
            get {
                return ResourceManager.GetString("Director_RelatedAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the type and reason for the pathway..
        /// </summary>
        internal static string Director_Type {
            get {
                return ResourceManager.GetString("Director_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A numeric value which identifies the specific error type..
        /// </summary>
        internal static string Error_Code {
            get {
                return ResourceManager.GetString("Error_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A sentence or paragraph providing details about the error..
        /// </summary>
        internal static string Error_Message {
            get {
                return ResourceManager.GetString("Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A descriptive name that is associated with the error code..
        /// </summary>
        internal static string Error_Name {
            get {
                return ResourceManager.GetString("Error_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the day value..
        /// </summary>
        internal static string Eventor_Day {
            get {
                return ResourceManager.GetString("Eventor_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the hour value (UTC)..
        /// </summary>
        internal static string Eventor_Hour {
            get {
                return ResourceManager.GetString("Eventor_Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the minute value (UTC)..
        /// </summary>
        internal static string Eventor_Minute {
            get {
                return ResourceManager.GetString("Eventor_Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the month value..
        /// </summary>
        internal static string Eventor_Month {
            get {
                return ResourceManager.GetString("Eventor_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the second value (UTC)..
        /// </summary>
        internal static string Eventor_Second {
            get {
                return ResourceManager.GetString("Eventor_Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the significance of this point in time..
        /// </summary>
        internal static string Eventor_Type {
            get {
                return ResourceManager.GetString("Eventor_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the year value..
        /// </summary>
        internal static string Eventor_Year {
            get {
                return ResourceManager.GetString("Eventor_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Describes the type of information (and/or level of confidence) provided by a particular Factor. Example assertions include: Fact, Opinion, Guess, etc..
        /// </summary>
        internal static string Factor_AssertionType {
            get {
                return ResourceManager.GetString("Factor_AssertionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This element defines the relationship between the primary and related Artifact..
        /// </summary>
        internal static string Factor_Descriptor {
            get {
                return ResourceManager.GetString("Factor_Descriptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This element creates a directional pathway between the primary and related Artifacts..
        /// </summary>
        internal static string Factor_Director {
            get {
                return ResourceManager.GetString("Factor_Director", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This element applies the concept of time..
        /// </summary>
        internal static string Factor_Eventor {
            get {
                return ResourceManager.GetString("Factor_Eventor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the type of information and/or level of confidence..
        /// </summary>
        internal static string Factor_FactorAssertion {
            get {
                return ResourceManager.GetString("Factor_FactorAssertion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This element applies a name or identifier..
        /// </summary>
        internal static string Factor_Identor {
            get {
                return ResourceManager.GetString("Factor_Identor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies whether this !Factor helps to directly and uniquely define the primary Artifact..
        /// </summary>
        internal static string Factor_IsDefining {
            get {
                return ResourceManager.GetString("Factor_IsDefining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This element provides a geographical or relative position..
        /// </summary>
        internal static string Factor_Locator {
            get {
                return ResourceManager.GetString("Factor_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A summary of the !Factor&apos;s intended meaning or purpose. This is useful in cases when the !Factor is vague, complex, or confusing. It can help resolve issues in cases where the Factor&apos;s Elements inaccurately model the intended meaning. Typically, this value is not written directly by a User; the App should have enough information about a particular !Factor-creating action to form a reasonable sentence or phrase..
        /// </summary>
        internal static string Factor_Note {
            get {
                return ResourceManager.GetString("Factor_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This element applies a numeric axis and value..
        /// </summary>
        internal static string Factor_Vector {
            get {
                return ResourceManager.GetString("Factor_Vector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information about the details and/or causes of the Fault..
        /// </summary>
        internal static string Fault_Message {
            get {
                return ResourceManager.GetString("Fault_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        internal static string Home_Name {
            get {
                return ResourceManager.GetString("Home_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The complete list of services..
        /// </summary>
        internal static string Home_Services {
            get {
                return ResourceManager.GetString("Home_Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        internal static string Home_Uri {
            get {
                return ResourceManager.GetString("Home_Uri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the value&apos;s purpose or intent..
        /// </summary>
        internal static string Identor_Type {
            get {
                return ResourceManager.GetString("Identor_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A text-based value that can represent names, numbers, IDs, GUIDs, etc..
        /// </summary>
        internal static string Identor_Value {
            get {
                return ResourceManager.GetString("Identor_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A secondary label or identifier, used to resolve unique-name conflicts..
        /// </summary>
        internal static string Instance_Disamb {
            get {
                return ResourceManager.GetString("Instance_Disamb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A descriptive name or title..
        /// </summary>
        internal static string Instance_Name {
            get {
                return ResourceManager.GetString("Instance_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A summary of the !Instance&apos;s intended meaning or purpose. This can resolve confusion in cases where an !Instance has vague or missing Factors..
        /// </summary>
        internal static string Instance_Note {
            get {
                return ResourceManager.GetString("Instance_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        internal static string Link_FromType {
            get {
                return ResourceManager.GetString("Link_FromType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        internal static string Link_ToType {
            get {
                return ResourceManager.GetString("Link_ToType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the spatial context of the coordinate..
        /// </summary>
        internal static string Locator_Type {
            get {
                return ResourceManager.GetString("Locator_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A value representing longitude, time/progress, width, or a particular three-dimensional axis..
        /// </summary>
        internal static string Locator_ValueX {
            get {
                return ResourceManager.GetString("Locator_ValueX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A value representing latitude, height, or a particular three-dimensional axis..
        /// </summary>
        internal static string Locator_ValueY {
            get {
                return ResourceManager.GetString("Locator_ValueY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A value representing elevation or a particular three-dimensional axis..
        /// </summary>
        internal static string Locator_ValueZ {
            get {
                return ResourceManager.GetString("Locator_ValueZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the Member&apos;s state and/or access privileges..
        /// </summary>
        internal static string Member_Type {
            get {
                return ResourceManager.GetString("Member_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current day of the month..
        /// </summary>
        internal static string MetaTime_Day {
            get {
                return ResourceManager.GetString("MetaTime_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current hour (using 24-hour time)..
        /// </summary>
        internal static string MetaTime_Hour {
            get {
                return ResourceManager.GetString("MetaTime_Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current millisecond..
        /// </summary>
        internal static string MetaTime_Millisecond {
            get {
                return ResourceManager.GetString("MetaTime_Millisecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current minute..
        /// </summary>
        internal static string MetaTime_Minute {
            get {
                return ResourceManager.GetString("MetaTime_Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current month..
        /// </summary>
        internal static string MetaTime_Month {
            get {
                return ResourceManager.GetString("MetaTime_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current second..
        /// </summary>
        internal static string MetaTime_Second {
            get {
                return ResourceManager.GetString("MetaTime_Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Unix timestamp value (in milliseconds)..
        /// </summary>
        internal static string MetaTime_Timestamp {
            get {
                return ResourceManager.GetString("MetaTime_Timestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The timezone used by the time metrics..
        /// </summary>
        internal static string MetaTime_Timezone {
            get {
                return ResourceManager.GetString("MetaTime_Timezone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current year..
        /// </summary>
        internal static string MetaTime_Year {
            get {
                return ResourceManager.GetString("MetaTime_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The day of the month that this build was released..
        /// </summary>
        internal static string MetaVersion_Day {
            get {
                return ResourceManager.GetString("MetaVersion_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The major revision number for this build. This value is only incremented in cases where significant or important changes have occurred. These changes may introduce backwards-incompatability with previous builds..
        /// </summary>
        internal static string MetaVersion_Major {
            get {
                return ResourceManager.GetString("MetaVersion_Major", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minor revision number for this build. This value is incremented in cases when substantial functionality or improvements are introduced. It may also occur when certain functionality becomes deprecated..
        /// </summary>
        internal static string MetaVersion_Minor {
            get {
                return ResourceManager.GetString("MetaVersion_Minor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The month that this build was released..
        /// </summary>
        internal static string MetaVersion_Month {
            get {
                return ResourceManager.GetString("MetaVersion_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The patch revision number for this build. This value is incremented when bug fixes or other internal changes occur..
        /// </summary>
        internal static string MetaVersion_Patch {
            get {
                return ResourceManager.GetString("MetaVersion_Patch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The revision text is derived from internal build information. It may be safely omitted from the build&apos;s version string..
        /// </summary>
        internal static string MetaVersion_Revision {
            get {
                return ResourceManager.GetString("MetaVersion_Revision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This build&apos;s full version string, in the format: &quot;Major.Minor.Patch.Revision&quot;..
        /// </summary>
        internal static string MetaVersion_Version {
            get {
                return ResourceManager.GetString("MetaVersion_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The year that this build was released..
        /// </summary>
        internal static string MetaVersion_Year {
            get {
                return ResourceManager.GetString("MetaVersion_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A code that maps to various authentication information. Notably, it is refers to exactly one App and at most one User..
        /// </summary>
        internal static string OauthAccess_AccessToken {
            get {
                return ResourceManager.GetString("OauthAccess_AccessToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of seconds until the access token expires..
        /// </summary>
        internal static string OauthAccess_ExpiresIn {
            get {
                return ResourceManager.GetString("OauthAccess_ExpiresIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A code that refreshes the authentication session for an expired OAuth access token. App-only access tokens do not include a refresh token; instead, the App should [[request a new access token|Oper|Oauth.AccessTokenClientCredentials]]..
        /// </summary>
        internal static string OauthAccess_RefreshToken {
            get {
                return ResourceManager.GetString("OauthAccess_RefreshToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For the current Fabric OAuth implementation, this value is always equal to &quot;bearer&quot;..
        /// </summary>
        internal static string OauthAccess_TokenType {
            get {
                return ResourceManager.GetString("OauthAccess_TokenType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error code as defined by the OAuth 2.0 specification..
        /// </summary>
        internal static string OauthError_Error {
            get {
                return ResourceManager.GetString("OauthError_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provides specific details about the error. A single error code may have one or more possible error descriptions..
        /// </summary>
        internal static string OauthError_ErrorDesc {
            get {
                return ResourceManager.GetString("OauthError_ErrorDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this code (also called the &apos;authorization code&apos;) to generate a new OAuth access token. For security purposes, each code is valid for a single use, and expires 120 seconds after creation..
        /// </summary>
        internal static string OauthLogin_Code {
            get {
                return ResourceManager.GetString("OauthLogin_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error code as defined by the OAuth 2.0 specification..
        /// </summary>
        internal static string OauthLogin_Error {
            get {
                return ResourceManager.GetString("OauthLogin_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provides specific details about the error. A single error code may have one or more possible error descriptions. For use in the redirect URI, this string uses a &apos;+&apos; character in place of each space character..
        /// </summary>
        internal static string OauthLogin_ErrorDesc {
            get {
                return ResourceManager.GetString("OauthLogin_ErrorDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the &apos;state&apos; value that the App provided in the original Oauth request. For security reasons, the App should reject the response if the original and returned values are not equal..
        /// </summary>
        internal static string OauthLogin_State {
            get {
                return ResourceManager.GetString("OauthLogin_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifies a particular OAuth session..
        /// </summary>
        internal static string OauthLogout_AccessToken {
            get {
                return ResourceManager.GetString("OauthLogout_AccessToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Describes the result of the logout attempt. Successful logout attempts return a value of 1..
        /// </summary>
        internal static string OauthLogout_Success {
            get {
                return ResourceManager.GetString("OauthLogout_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data type of this object..
        /// </summary>
        internal static string Object_Obj {
            get {
                return ResourceManager.GetString("Object_Obj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains the result of the request as a list of zero or more Objects..
        /// </summary>
        internal static string Response_Data {
            get {
                return ResourceManager.GetString("Response_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If an error occurred, this contains information about the problem. Typically, the Data value is null when an Error value is present..
        /// </summary>
        internal static string Response_Error {
            get {
                return ResourceManager.GetString("Response_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The time (in milliseconds) that it took the server(s) to complete this request..
        /// </summary>
        internal static string Response_TotalMs {
            get {
                return ResourceManager.GetString("Response_TotalMs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service name..
        /// </summary>
        internal static string Service_Name {
            get {
                return ResourceManager.GetString("Service_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The complete list of operations for this service..
        /// </summary>
        internal static string Service_Operations {
            get {
                return ResourceManager.GetString("Service_Operations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Append this path to the current URI to obtain details about this service..
        /// </summary>
        internal static string Service_Uri {
            get {
                return ResourceManager.GetString("Service_Uri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The required HTTP method..
        /// </summary>
        internal static string ServiceOperation_Method {
            get {
                return ResourceManager.GetString("ServiceOperation_Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A descriptive name for this operation..
        /// </summary>
        internal static string ServiceOperation_Name {
            get {
                return ResourceManager.GetString("ServiceOperation_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of Object returned by this operation..
        /// </summary>
        internal static string ServiceOperation_Return {
            get {
                return ResourceManager.GetString("ServiceOperation_Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Append this value to the current URI (and use the correct HTTP method) to invoke this operation..
        /// </summary>
        internal static string ServiceOperation_Uri {
            get {
                return ResourceManager.GetString("ServiceOperation_Uri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        internal static string TravStep_Name {
            get {
                return ResourceManager.GetString("TravStep_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        internal static string TravStep_Return {
            get {
                return ResourceManager.GetString("TravStep_Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        internal static string TravStep_Uri {
            get {
                return ResourceManager.GetString("TravStep_Uri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A unique, valid absolute URL. The string must include the link&apos;s protocol (such as &apos;http://&apos;)..
        /// </summary>
        internal static string Url_FullPath {
            get {
                return ResourceManager.GetString("Url_FullPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A descriptive name or title..
        /// </summary>
        internal static string Url_Name {
            get {
                return ResourceManager.GetString("Url_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A unique username..
        /// </summary>
        internal static string User_Name {
            get {
                return ResourceManager.GetString("User_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies its value&apos;s boundaries and context..
        /// </summary>
        internal static string Vector_Type {
            get {
                return ResourceManager.GetString("Vector_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies its value&apos;s unit of measurement..
        /// </summary>
        internal static string Vector_Unit {
            get {
                return ResourceManager.GetString("Vector_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies its value&apos;s order of magnitude..
        /// </summary>
        internal static string Vector_UnitPrefix {
            get {
                return ResourceManager.GetString("Vector_UnitPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An integral value which is to be plotted along the specified axis. This value must account for the choice of prefix. After being multiplied by the prefix magnitude, the value must fall within the bounds specified by VectorType. Before prefix multiplication, this value must be between –9,223,372,036,854,775,808 and 9,223,372,036,854,775,807..
        /// </summary>
        internal static string Vector_Value {
            get {
                return ResourceManager.GetString("Vector_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A unique identifier for this !Vertex..
        /// </summary>
        internal static string Vertex_Id {
            get {
                return ResourceManager.GetString("Vertex_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date/time of creation..
        /// </summary>
        internal static string Vertex_Timestamp {
            get {
                return ResourceManager.GetString("Vertex_Timestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        internal static string Vertex_VertexType {
            get {
                return ResourceManager.GetString("Vertex_VertexType", resourceCulture);
            }
        }
    }
}
