namespace Fabric.New.Database.Init.Setups {

	/*================================================================================================*/
	public enum SetupVertexId : long {
		Email_DP_ITF = 1,
		User_FabData,
		App_FabSys,
		Mem_FabFabData,

		Email_Zach_AEI,
		User_Zach,
		Mem_FabZach,

		Email_MKin_Gmail,
		User_Mel,
		Mem_FabMel,

		Email_PhoApp_ZK,
		User_GalData,
		Mem_FabGalData,
		App_KinPhoGal,
		Mem_GalGalData,
		Mem_GalZach,

		Email_EJ_ZK,
		User_Ellie,
		Mem_FabEllie,
		Mem_GalEllie,

		Mem_GalMel,

		Email_PJ_ZK,
		User_Penny,
		Mem_FabPenny,

		Email_FabApp_Book,
		User_BookData,
		Mem_FabBookData,
		App_Bookmarker,
		Mem_BookBookData,

		Mem_BookZach,
		Mem_BookMel,
		Mem_GalBookDataNone,
		Mem_GalPenny,
		Mem_BookEllie,
		Mem_BookPenny,

		Oau_GalZach_Past,
		Oau_GalMel_Past,
		Oau_GalGalData_Past,
		Oau_GalEllie_Past,
		Oau_BookBookData_Past,
		Oau_BookMel_Past,
		Oau_GalZach,
		Oau_GalMel,
		Oau_GalGalData,
		Oau_BookZach,
		Oau_BookMel,
		Oau_FabZach,

		Url_ZachKin,
		Url_Google,
		Url_ZachFb,
		Url_YahooFin,
		Url_CutePhoto,

		Cla_Human,
		Cla_Male,
		Cla_Female,
		Cla_Name,
		Cla_Legal,
		Cla_Home,
		Cla_Muskegon,
		Ins_Neimeyer,
		Ins_CampusView,
		Cla_Location,
		Ins_AppleRidge,
		Cla_Caldonia,
		Ins_FabricPlat,
		Cla_Attend,
		Ins_RPHS,
		Cla_GradePointAvg,
		Cla_ACTTest,
		Cla_Overall,
		Ins_GrandValley,
		Ins_Aei,
		Cla_Software,
		Cla_Art,
		Cla_Graphics,
		Cla_Games,
		Cla_Music,
		Cla_Evolution,
		Cla_ArtlIntel,
		Cla_Physics,
		Cla_Height,
		Cla_Weight,
		Cla_Beauty,
		Ins_TigersGame,
		Cla_MlbGame,
		Ins_DetroitTigers,
		Ins_BostonRedSox,
		Ins_ComericaPark,
		Ins_Bottom11,
		Cla_Inning,
		Cla_Attendance,
		Cla_Excitement,
		Cla_WebPage,
		Ins_CutePhoto,
		Cla_Photo,
		Cla_Digital,
		Cla_Favorite,
		Cla_FocalLength,
		Cla_Exposure,
		Cla_FStop,
		Cla_IsoSpeed,
		Cla_Quality,
		Cla_Subject,
		Cla_Object,
		Cla_Smile,
		Cla_Pigtail,
		Cla_Rope,
		Cla_Blue,
		Cla_Swing,
		Ins_FisherPrice,
		Cla_Happiness,
		Cla_Fun,
		Cla_Cuteness,

		Fac_FZ_Zach_Human_IsA_Male_Def,
		Fac_FZ_Zach_Human_Start_Def,
		Fac_FZ_Zach_Name_ZK,
		Fac_FZ_Zach_Name_Legal_ZRK_Def,
		Fac_FZ_Zach_Muskegon_FoundIn_Home_Start,
		Fac_FZ_Zach_Muskegon_FoundIn_Home_End,
		Fac_FZ_Zach_Neimeyer_FoundIn_Home_Start,
		Fac_FZ_Zach_Neimeyer_FoundIn_Home_End,
		Fac_FZ_Zach_CampView_FoundIn_Home_Start,
		Fac_FZ_Zach_CampView_FoundIn_Home_End,
		Fac_FZ_Zach_AppRidge_FoundIn_Home_Start,
		Fac_FZ_Zach_AppRidge_FoundIn_Home_End,
		Fac_FZ_Zach_Caledonia_FoundIn_Home_Start,
		Fac_FZ_Zach_Fabric_ViewSuggLearn,
		Fac_FZ_Zach_Mel_ViewSuggView,
		Fac_FZ_Zach_RPHS_PartIn_Attend_Start,
		Fac_FZ_Zach_RPHS_PartIn_Attend_End,
		Fac_FZ_Zach_RPHS_PartIn_Attend_GPA,
		Fac_FZ_Zach_ACT_PartIn_Overall,
		Fac_FZ_Zach_GVSU_PartIn_Attend_Start,
		Fac_FZ_Zach_GVSU_PartIn_Attend_End,
		Fac_FZ_Zach_AEI_EdgeTo_ViewSuggView,
		Fac_FZ_Zach_Software_Produce,
		Fac_FZ_Zach_Art_Produce,
		Fac_FZ_Zach_Graphics_Produce,
		Fac_FZ_Zach_Games_Produce,
		Fac_FZ_Zach_Music_Produce,
		Fac_FZ_Zach_Software_Interest,
		Fac_FZ_Zach_Graphics_Interest,
		Fac_FZ_Zach_Evolution_Interest,
		Fac_FZ_Zach_Games_Interest,
		Fac_FZ_Zach_ArtIntel_Interest,
		Fac_FZ_Zach_Physics_Interest,
		Fac_FZ_Zach_Human_IsA_Height,
		Fac_FZ_Zach_Human_IsA_WeightA,
		Fac_FZ_Zach_Human_IsA_WeightB,
		Fac_FZ_Zach_Human_IsA_WeightC_Del,
		Fac_FZ_Zach_Human_IsA_WeightD_Del,
		Fac_FZ_Zach_Human_IsA_WeightE,
		Fac_FZ_Zach_Human_IsA_WeightF,

		Fac_FM_Mel_Human_IsA_Female_Def,
		Fac_FM_Mel_Human_IsA_Start_Def,
		Fac_FM_Mel_Name_HasA_MM_End,
		Fac_FM_Mel_Name_HasA_MK_Start,
		Fac_FM_Mel_Name_HasA_Legal_MRM_End_Def,
		Fac_FM_Mel_Name_HasA_Legal_MRK_Start_Def,
		Fac_FM_Mel_Caldonia_FoundIn_Home,
		Fac_FM_Mel_Zach_ViewSuggView,
		Fac_FZ_Mel_Human_IsA_Beauty,
		Fac_FM_Mel_Human_IsA_Height,

		Fac_BB_Game_MlbGame_IsA_Def,
		Fac_BB_Game_MlbGame_IsA_Start_Def,
		Fac_BB_Game_Tigers_HasA_Def,
		Fac_BB_Game_RedSox_HasA_Def,
		Fac_BB_Game_Comerica_FoundIn_Def,
		Fac_BB_Game_MlbGame_IsA_End,
		Fac_BB_Game_MlbGame_IsA_Innings,
		Fac_BZ_Game_MlbGame_IsA_Attendance,
		Fac_BZ_Game_Bot11_HasA,
		Fac_BZ_Game_MlbGame_IsA_Excite,
		Fac_BM_Game_MlbGame_IsA_Excite,
		Fac_FE_Game_MlbGame_IsA_Excite,
		Fac_FP_Game_MlbGame_IsA_Excite,

		Fac_BB_Bot11_Inning_IsA_Def,
		Fac_BB_Bot11_Game_Belongs_Def,
		Fac_BB_Bot11_Inning_IsA_Start,
		Fac_BB_Bot11_Inning_IsA_End,
		Fac_BZ_Bot11_Inning_IsA_Excite,
		Fac_BM_Bot11_Inning_IsA_Excite,
		Fac_FE_Bot11_Inning_IsA_Excite,
		Fac_FP_Bot11_Inning_IsA_Excite,

		Fac_GG_CuteUrl_WebPage_IsA_Def,
		Fac_GG_CuteUrl_CutePho_Refers_Def,
		Fac_GG_CuteUrl_KinPhoGal_Belongs_Def,

		Fac_GG_CutePho_Photo_IsA_Digi_Def,
		Fac_GG_CutePho_Photo_IsA_Occur_Def,
		Fac_GG_CutePho_Photo_IsA_Key4165_Def,
		Fac_GG_CutePho_Photo_IsA_TextImg9203,
		Fac_GG_CutePho_KinPhoGal_Belongs_Def,
		Fac_GG_CutePho_Receives_Favorite,
		Fac_GG_CutePho_Photo_IsA_Focal,
		Fac_GZ_CutePho_Photo_IsA_Focal,
		Fac_GM_CutePho_Photo_IsA_Focal,
		Fac_GG_CutePho_Photo_IsA_Expose,
		Fac_GG_CutePho_Photo_IsA_FStop,
		Fac_GG_CutePho_Photo_IsA_Iso,
		Fac_GG_CutePho_Photo_IsA_Quality,
		Fac_GM_CutePho_Ellie_Refers_Subject,
		Fac_GM_CutePho_Smile_HasA_Subject,
		Fac_GM_CutePho_Pigtail_HasA_Subject,
		Fac_GM_CutePho_Rope_HasA_Object_Blue,
		Fac_GM_CutePho_Swing_HasA_Object,
		Fac_GZ_CutePho_Ellie_Refers_Subject,
		Fac_GZ_CutePho_Fisher_Refers_Object,
		Fac_GZ_CutePho_Swing_Refers_Object,
		Fac_GM_CutePho_Happiness_Emotes,
		Fac_GM_CutePho_Fun_Emotes,
		Fac_GZ_CutePho_Photo_IsA_Occur_QualityA,
		Fac_GZ_CutePho_Photo_IsA_Occur_QualityB,
		Fac_GZ_CutePho_Photo_IsA_Occur_QualityC,
		Fac_GM_CutePho_Photo_IsA_Occur_Quality,
		Fac_GZ_CutePho_Photo_IsA_Occur_Cuteness,
		Fac_GM_CutePho_Photo_IsA_Occur_Cuteness,
		Fac_GE_CutePho_Photo_IsA_Occur_Cuteness,
	}


	/*================================================================================================*/
	public enum SetupArtifactId : long {
		App_FabSys = SetupVertexId.App_FabSys,
		App_KinPhoGal = SetupVertexId.App_KinPhoGal,
		App_Bookmarker = SetupVertexId.App_Bookmarker,

		User_FabData = SetupVertexId.User_FabData,
		User_Zach = SetupVertexId.User_Zach,
		User_Mel = SetupVertexId.User_Mel,
		User_GalData = SetupVertexId.User_GalData,
		User_Ellie = SetupVertexId.User_Ellie,
		User_Penny = SetupVertexId.User_Penny,
		User_BookData = SetupVertexId.User_BookData,

		Url_ZachKin = SetupVertexId.Url_ZachKin,
		Url_Google = SetupVertexId.Url_Google,
		Url_ZachFb = SetupVertexId.Url_ZachFb,
		Url_YahooFin = SetupVertexId.Url_YahooFin,
		Url_CutePhoto = SetupVertexId.Url_CutePhoto,

		Cla_Human = SetupVertexId.Cla_Human,
		Cla_Male = SetupVertexId.Cla_Male,
		Cla_Female = SetupVertexId.Cla_Female,
		Cla_Name = SetupVertexId.Cla_Name,
		Cla_Legal = SetupVertexId.Cla_Legal,
		Cla_Home = SetupVertexId.Cla_Home,
		Cla_Muskegon = SetupVertexId.Cla_Muskegon,
		Ins_Neimeyer = SetupVertexId.Ins_Neimeyer,
		Ins_CampusView = SetupVertexId.Ins_CampusView,
		Cla_Location = SetupVertexId.Cla_Location,
		Ins_AppleRidge = SetupVertexId.Ins_AppleRidge,
		Cla_Caldonia = SetupVertexId.Cla_Caldonia,
		Ins_FabricPlat = SetupVertexId.Ins_FabricPlat,
		Cla_Attend = SetupVertexId.Cla_Attend,
		Ins_RPHS = SetupVertexId.Ins_RPHS,
		Cla_GradePointAvg = SetupVertexId.Cla_GradePointAvg,
		Cla_ACTTest = SetupVertexId.Cla_ACTTest,
		Cla_Overall = SetupVertexId.Cla_Overall,
		Ins_GrandValley = SetupVertexId.Ins_GrandValley,
		Ins_Aei = SetupVertexId.Ins_Aei,
		Cla_Software = SetupVertexId.Cla_Software,
		Cla_Art = SetupVertexId.Cla_Art,
		Cla_Graphics = SetupVertexId.Cla_Graphics,
		Cla_Games = SetupVertexId.Cla_Games,
		Cla_Music = SetupVertexId.Cla_Music,
		Cla_Evolution = SetupVertexId.Cla_Evolution,
		Cla_ArtlIntel = SetupVertexId.Cla_ArtlIntel,
		Cla_Physics = SetupVertexId.Cla_Physics,
		Cla_Height = SetupVertexId.Cla_Height,
		Cla_Weight = SetupVertexId.Cla_Weight,
		Cla_Beauty = SetupVertexId.Cla_Beauty,
		Ins_TigersGame = SetupVertexId.Ins_TigersGame,
		Cla_MlbGame = SetupVertexId.Cla_MlbGame,
		Ins_DetroitTigers = SetupVertexId.Ins_DetroitTigers,
		Ins_BostonRedSox = SetupVertexId.Ins_BostonRedSox,
		Ins_ComericaPark = SetupVertexId.Ins_ComericaPark,
		Ins_Bottom11 = SetupVertexId.Ins_Bottom11,
		Cla_Inning = SetupVertexId.Cla_Inning,
		Cla_Attendance = SetupVertexId.Cla_Attendance,
		Cla_Excitement = SetupVertexId.Cla_Excitement,
		Cla_WebPage = SetupVertexId.Cla_WebPage,
		Ins_CutePhoto = SetupVertexId.Ins_CutePhoto,
		Cla_Photo = SetupVertexId.Cla_Photo,
		Cla_Digital = SetupVertexId.Cla_Digital,
		Cla_Favorite = SetupVertexId.Cla_Favorite,
		Cla_FocalLength = SetupVertexId.Cla_FocalLength,
		Cla_Exposure = SetupVertexId.Cla_Exposure,
		Cla_FStop = SetupVertexId.Cla_FStop,
		Cla_IsoSpeed = SetupVertexId.Cla_IsoSpeed,
		Cla_Quality = SetupVertexId.Cla_Quality,
		Cla_Subject = SetupVertexId.Cla_Subject,
		Cla_Object = SetupVertexId.Cla_Object,
		Cla_Smile = SetupVertexId.Cla_Smile,
		Cla_Pigtail = SetupVertexId.Cla_Pigtail,
		Cla_Rope = SetupVertexId.Cla_Rope,
		Cla_Blue = SetupVertexId.Cla_Blue,
		Cla_Swing = SetupVertexId.Cla_Swing,
		Ins_FisherPrice = SetupVertexId.Ins_FisherPrice,
		Cla_Happiness = SetupVertexId.Cla_Happiness,
		Cla_Fun = SetupVertexId.Cla_Fun,
		Cla_Cuteness = SetupVertexId.Cla_Cuteness,
	}


	/*================================================================================================*/
	public enum SetupUserId : long {
		FabData = SetupArtifactId.User_FabData,
		Zach = SetupArtifactId.User_Zach,
		Mel = SetupArtifactId.User_Mel,
		GalData = SetupArtifactId.User_GalData,
		Ellie = SetupArtifactId.User_Ellie,
		Penny = SetupArtifactId.User_Penny,
		BookData = SetupArtifactId.User_BookData,
	}


	/*================================================================================================*/
	public enum SetupAppId : long {
		FabSys = SetupArtifactId.App_FabSys,
		KinPhoGal = SetupArtifactId.App_KinPhoGal,
		Bookmarker = SetupArtifactId.App_Bookmarker,
	}


	/*================================================================================================*/
	public enum SetupUrlId : long {
		ZachKin = SetupArtifactId.Url_ZachKin,
		Google = SetupArtifactId.Url_Google,
		ZachFb = SetupArtifactId.Url_ZachFb,
		YahooFin = SetupArtifactId.Url_YahooFin,
		CutePhoto = SetupArtifactId.Url_CutePhoto,
	}


	/*================================================================================================*/
	public enum SetupClassId : long {
		Human = SetupArtifactId.Cla_Human,
		Male = SetupArtifactId.Cla_Male,
		Female = SetupArtifactId.Cla_Female,
		Name = SetupArtifactId.Cla_Name,
		Legal = SetupArtifactId.Cla_Legal,
		Home = SetupArtifactId.Cla_Home,
		Muskegon = SetupArtifactId.Cla_Muskegon,
		Location = SetupArtifactId.Cla_Location,
		Caldonia = SetupArtifactId.Cla_Caldonia,
		Attend = SetupArtifactId.Cla_Attend,
		GradePointAvg = SetupArtifactId.Cla_GradePointAvg,
		ACTTest = SetupArtifactId.Cla_ACTTest,
		Overall = SetupArtifactId.Cla_Overall,
		Software = SetupArtifactId.Cla_Software,
		Art = SetupArtifactId.Cla_Art,
		Graphics = SetupArtifactId.Cla_Graphics,
		Games = SetupArtifactId.Cla_Games,
		Music = SetupArtifactId.Cla_Music,
		Evolution = SetupArtifactId.Cla_Evolution,
		ArtificialIntel = SetupArtifactId.Cla_ArtlIntel,
		Physics = SetupArtifactId.Cla_Physics,
		Height = SetupArtifactId.Cla_Height,
		Weight = SetupArtifactId.Cla_Weight,
		Beauty = SetupArtifactId.Cla_Beauty,
		MlbGame = SetupArtifactId.Cla_MlbGame,
		Inning = SetupArtifactId.Cla_Inning,
		Attendance = SetupArtifactId.Cla_Attendance,
		Excitement = SetupArtifactId.Cla_Excitement,
		WebPage = SetupArtifactId.Cla_WebPage,
		Photo = SetupArtifactId.Cla_Photo,
		Digital = SetupArtifactId.Cla_Digital,
		Favorite = SetupArtifactId.Cla_Favorite,
		FocalLength = SetupArtifactId.Cla_FocalLength,
		Exposure = SetupArtifactId.Cla_Exposure,
		FStop = SetupArtifactId.Cla_FStop,
		IsoSpeed = SetupArtifactId.Cla_IsoSpeed,
		Quality = SetupArtifactId.Cla_Quality,
		Subject = SetupArtifactId.Cla_Subject,
		Object = SetupArtifactId.Cla_Object,
		Smile = SetupArtifactId.Cla_Smile,
		Pigtail = SetupArtifactId.Cla_Pigtail,
		Rope = SetupArtifactId.Cla_Rope,
		Blue = SetupArtifactId.Cla_Blue,
		Swing = SetupArtifactId.Cla_Swing,
		Happiness = SetupArtifactId.Cla_Happiness,
		Fun = SetupArtifactId.Cla_Fun,
		Cuteness = SetupArtifactId.Cla_Cuteness,
	}


	/*================================================================================================*/
	public enum SetupInstanceId : long {
		Neimeyer = SetupArtifactId.Ins_Neimeyer,
		CampusView = SetupArtifactId.Ins_CampusView,
		AppleRidge = SetupArtifactId.Ins_AppleRidge,
		FabricPlatform = SetupArtifactId.Ins_FabricPlat,
		ReethsPufferHS = SetupArtifactId.Ins_RPHS,
		GrandValley = SetupArtifactId.Ins_GrandValley,
		AestheticInteractive = SetupArtifactId.Ins_Aei,
		TigersGame = SetupArtifactId.Ins_TigersGame,
		DetroitTigers = SetupArtifactId.Ins_DetroitTigers,
		BostonRedSox = SetupArtifactId.Ins_BostonRedSox,
		ComericaPark = SetupArtifactId.Ins_ComericaPark,
		Bottom11 = SetupArtifactId.Ins_Bottom11,
		CutePhoto = SetupArtifactId.Ins_CutePhoto,
		FisherPrice = SetupArtifactId.Ins_FisherPrice,
	}


	/*================================================================================================*/
	public enum SetupEmailId : long {
		DP_ITF = SetupVertexId.Email_DP_ITF,
		Zach_AEI = SetupVertexId.Email_Zach_AEI,
		MKin_Gmail = SetupVertexId.Email_MKin_Gmail,
		PhoApp_ZK = SetupVertexId.Email_PhoApp_ZK,
		EJ_ZK = SetupVertexId.Email_EJ_ZK,
		PJ_ZK = SetupVertexId.Email_PJ_ZK,
		FabApp_Book = SetupVertexId.Email_FabApp_Book,
	}


	/*================================================================================================*/
	public enum SetupMemberId : long {
		FabFabData = SetupVertexId.Mem_FabFabData,
		FabZach = SetupVertexId.Mem_FabZach,
		FabMel = SetupVertexId.Mem_FabMel,
		FabGalData = SetupVertexId.Mem_FabGalData,
		GalGalData = SetupVertexId.Mem_GalGalData,
		GalZach = SetupVertexId.Mem_GalZach,
		FabEllie = SetupVertexId.Mem_FabEllie,
		GalEllie = SetupVertexId.Mem_GalEllie,
		GalMel = SetupVertexId.Mem_GalMel,
		FabPenny = SetupVertexId.Mem_FabPenny,
		FabBookData = SetupVertexId.Mem_FabBookData,
		BookBookData = SetupVertexId.Mem_BookBookData,
		BookZach = SetupVertexId.Mem_BookZach,
		BookMel = SetupVertexId.Mem_BookMel,
		GalBookDataNone = SetupVertexId.Mem_GalBookDataNone,
		GalPenny = SetupVertexId.Mem_GalPenny,
		BookEllie = SetupVertexId.Mem_BookEllie,
		BookPenny = SetupVertexId.Mem_BookPenny,
	}


	/*================================================================================================*/
	public enum OauthAccessId : long {
		GalZach_Past = SetupVertexId.Oau_GalZach_Past,
		GalMel_Past = SetupVertexId.Oau_GalMel_Past,
		GalGalData_Past = SetupVertexId.Oau_GalGalData_Past,
		GalEllie_Past = SetupVertexId.Oau_GalEllie_Past,
		BookBookData_Past = SetupVertexId.Oau_BookBookData_Past,
		BookMel_Past = SetupVertexId.Oau_BookMel_Past,
		GalZach = SetupVertexId.Oau_GalZach,
		GalMel = SetupVertexId.Oau_GalMel,
		GalGalData = SetupVertexId.Oau_GalGalData,
		BookZach = SetupVertexId.Oau_BookZach,
		BookMel = SetupVertexId.Oau_BookMel,
		FabZach = SetupVertexId.Oau_FabZach,
	}


	/*================================================================================================*/
	public enum SetupFactorId : long {
		FZ_Zach_Human_IsA_Male_Def = SetupVertexId.Fac_FZ_Zach_Human_IsA_Male_Def,
		FZ_Zach_Human_Start_Def = SetupVertexId.Fac_FZ_Zach_Human_Start_Def,
		FZ_Zach_Name_ZK = SetupVertexId.Fac_FZ_Zach_Name_ZK,
		FZ_Zach_Name_Legal_ZRK_Def = SetupVertexId.Fac_FZ_Zach_Name_Legal_ZRK_Def,
		FZ_Zach_Muskegon_FoundIn_Home_Start = SetupVertexId.Fac_FZ_Zach_Muskegon_FoundIn_Home_Start,
		FZ_Zach_Muskegon_FoundIn_Home_End = SetupVertexId.Fac_FZ_Zach_Muskegon_FoundIn_Home_End,
		FZ_Zach_Neimeyer_FoundIn_Home_Start = SetupVertexId.Fac_FZ_Zach_Neimeyer_FoundIn_Home_Start,
		FZ_Zach_Neimeyer_FoundIn_Home_End = SetupVertexId.Fac_FZ_Zach_Neimeyer_FoundIn_Home_End,
		FZ_Zach_CampView_FoundIn_Home_Start = SetupVertexId.Fac_FZ_Zach_CampView_FoundIn_Home_Start,
		FZ_Zach_CampView_FoundIn_Home_End = SetupVertexId.Fac_FZ_Zach_CampView_FoundIn_Home_End,
		FZ_Zach_AppRidge_FoundIn_Home_Start = SetupVertexId.Fac_FZ_Zach_AppRidge_FoundIn_Home_Start,
		FZ_Zach_AppRidge_FoundIn_Home_End = SetupVertexId.Fac_FZ_Zach_AppRidge_FoundIn_Home_End,
		FZ_Zach_Caledonia_FoundIn_Home_Start = SetupVertexId.Fac_FZ_Zach_Caledonia_FoundIn_Home_Start,
		FZ_Zach_Fabric_ViewSuggLearn = SetupVertexId.Fac_FZ_Zach_Fabric_ViewSuggLearn,
		FZ_Zach_Mel_ViewSuggView = SetupVertexId.Fac_FZ_Zach_Mel_ViewSuggView,
		FZ_Zach_RPHS_PartIn_Attend_Start = SetupVertexId.Fac_FZ_Zach_RPHS_PartIn_Attend_Start,
		FZ_Zach_RPHS_PartIn_Attend_End = SetupVertexId.Fac_FZ_Zach_RPHS_PartIn_Attend_End,
		FZ_Zach_RPHS_PartIn_Attend_GPA = SetupVertexId.Fac_FZ_Zach_RPHS_PartIn_Attend_GPA,
		FZ_Zach_ACT_PartIn_Overall = SetupVertexId.Fac_FZ_Zach_ACT_PartIn_Overall,
		FZ_Zach_GVSU_PartIn_Attend_Start = SetupVertexId.Fac_FZ_Zach_GVSU_PartIn_Attend_Start,
		FZ_Zach_GVSU_PartIn_Attend_End = SetupVertexId.Fac_FZ_Zach_GVSU_PartIn_Attend_End,
		FZ_Zach_AEI_EdgeTo_ViewSuggView = SetupVertexId.Fac_FZ_Zach_AEI_EdgeTo_ViewSuggView,
		FZ_Zach_Software_Produce = SetupVertexId.Fac_FZ_Zach_Software_Produce,
		FZ_Zach_Art_Produce = SetupVertexId.Fac_FZ_Zach_Art_Produce,
		FZ_Zach_Graphics_Produce = SetupVertexId.Fac_FZ_Zach_Graphics_Produce,
		FZ_Zach_Games_Produce = SetupVertexId.Fac_FZ_Zach_Games_Produce,
		FZ_Zach_Music_Produce = SetupVertexId.Fac_FZ_Zach_Music_Produce,
		FZ_Zach_Software_Interest = SetupVertexId.Fac_FZ_Zach_Software_Interest,
		FZ_Zach_Graphics_Interest = SetupVertexId.Fac_FZ_Zach_Graphics_Interest,
		FZ_Zach_Evolution_Interest = SetupVertexId.Fac_FZ_Zach_Evolution_Interest,
		FZ_Zach_Games_Interest = SetupVertexId.Fac_FZ_Zach_Games_Interest,
		FZ_Zach_ArtIntel_Interest = SetupVertexId.Fac_FZ_Zach_ArtIntel_Interest,
		FZ_Zach_Physics_Interest = SetupVertexId.Fac_FZ_Zach_Physics_Interest,
		FZ_Zach_Human_IsA_Height = SetupVertexId.Fac_FZ_Zach_Human_IsA_Height,
		FZ_Zach_Human_IsA_WeightA = SetupVertexId.Fac_FZ_Zach_Human_IsA_WeightA,
		FZ_Zach_Human_IsA_WeightB = SetupVertexId.Fac_FZ_Zach_Human_IsA_WeightB,
		FZ_Zach_Human_IsA_WeightC_Del = SetupVertexId.Fac_FZ_Zach_Human_IsA_WeightC_Del,
		FZ_Zach_Human_IsA_WeightD_Del = SetupVertexId.Fac_FZ_Zach_Human_IsA_WeightD_Del,
		FZ_Zach_Human_IsA_WeightE = SetupVertexId.Fac_FZ_Zach_Human_IsA_WeightE,
		FZ_Zach_Human_IsA_WeightF = SetupVertexId.Fac_FZ_Zach_Human_IsA_WeightF,

		FM_Mel_Human_IsA_Female_Def = SetupVertexId.Fac_FM_Mel_Human_IsA_Female_Def,
		FM_Mel_Human_IsA_Start_Def = SetupVertexId.Fac_FM_Mel_Human_IsA_Start_Def,
		FM_Mel_Name_HasA_MM_End = SetupVertexId.Fac_FM_Mel_Name_HasA_MM_End,
		FM_Mel_Name_HasA_MK_Start = SetupVertexId.Fac_FM_Mel_Name_HasA_MK_Start,
		FM_Mel_Name_HasA_Legal_MRM_End_Def = SetupVertexId.Fac_FM_Mel_Name_HasA_Legal_MRM_End_Def,
		FM_Mel_Name_HasA_Legal_MRK_Start_Def = SetupVertexId.Fac_FM_Mel_Name_HasA_Legal_MRK_Start_Def,
		FM_Mel_Caldonia_FoundIn_Home = SetupVertexId.Fac_FM_Mel_Caldonia_FoundIn_Home,
		FM_Mel_Zach_ViewSuggView = SetupVertexId.Fac_FM_Mel_Zach_ViewSuggView,
		FZ_Mel_Human_IsA_Beauty = SetupVertexId.Fac_FZ_Mel_Human_IsA_Beauty,
		FM_Mel_Human_IsA_Height = SetupVertexId.Fac_FM_Mel_Human_IsA_Height,

		BB_Game_MlbGame_IsA_Def = SetupVertexId.Fac_BB_Game_MlbGame_IsA_Def,
		BB_Game_MlbGame_IsA_Start_Def = SetupVertexId.Fac_BB_Game_MlbGame_IsA_Start_Def,
		BB_Game_Tigers_HasA_Def = SetupVertexId.Fac_BB_Game_Tigers_HasA_Def,
		BB_Game_RedSox_HasA_Def = SetupVertexId.Fac_BB_Game_RedSox_HasA_Def,
		BB_Game_Comerica_FoundIn_Def = SetupVertexId.Fac_BB_Game_Comerica_FoundIn_Def,
		BB_Game_MlbGame_IsA_End = SetupVertexId.Fac_BB_Game_MlbGame_IsA_End,
		BB_Game_MlbGame_IsA_Innings = SetupVertexId.Fac_BB_Game_MlbGame_IsA_Innings,
		BZ_Game_MlbGame_IsA_Attendance = SetupVertexId.Fac_BZ_Game_MlbGame_IsA_Attendance,
		BZ_Game_Bot11_HasA = SetupVertexId.Fac_BZ_Game_Bot11_HasA,
		BZ_Game_MlbGame_IsA_Excite = SetupVertexId.Fac_BZ_Game_MlbGame_IsA_Excite,
		BM_Game_MlbGame_IsA_Excite = SetupVertexId.Fac_BM_Game_MlbGame_IsA_Excite,
		FE_Game_MlbGame_IsA_Excite = SetupVertexId.Fac_FE_Game_MlbGame_IsA_Excite,
		FP_Game_MlbGame_IsA_Excite = SetupVertexId.Fac_FP_Game_MlbGame_IsA_Excite,

		BB_Bot11_Inning_IsA_Def = SetupVertexId.Fac_BB_Bot11_Inning_IsA_Def,
		BB_Bot11_Game_Belongs_Def = SetupVertexId.Fac_BB_Bot11_Game_Belongs_Def,
		BB_Bot11_Inning_IsA_Start = SetupVertexId.Fac_BB_Bot11_Inning_IsA_Start,
		BB_Bot11_Inning_IsA_End = SetupVertexId.Fac_BB_Bot11_Inning_IsA_End,
		BZ_Bot11_Inning_IsA_Excite = SetupVertexId.Fac_BZ_Bot11_Inning_IsA_Excite,
		BM_Bot11_Inning_IsA_Excite = SetupVertexId.Fac_BM_Bot11_Inning_IsA_Excite,
		FE_Bot11_Inning_IsA_Excite = SetupVertexId.Fac_FE_Bot11_Inning_IsA_Excite,
		FP_Bot11_Inning_IsA_Excite = SetupVertexId.Fac_FP_Bot11_Inning_IsA_Excite,

		GG_CuteUrl_WebPage_IsA_Def = SetupVertexId.Fac_GG_CuteUrl_WebPage_IsA_Def,
		GG_CuteUrl_CutePho_Refers_Def = SetupVertexId.Fac_GG_CuteUrl_CutePho_Refers_Def,
		GG_CuteUrl_KinPhoGal_Belongs_Def = SetupVertexId.Fac_GG_CuteUrl_KinPhoGal_Belongs_Def,

		GG_CutePho_Photo_IsA_Digi_Def = SetupVertexId.Fac_GG_CutePho_Photo_IsA_Digi_Def,
		GG_CutePho_Photo_IsA_Occur_Def = SetupVertexId.Fac_GG_CutePho_Photo_IsA_Occur_Def,
		GG_CutePho_Photo_IsA_Key4165_Def = SetupVertexId.Fac_GG_CutePho_Photo_IsA_Key4165_Def,
		GG_CutePho_Photo_IsA_TextImg9203 = SetupVertexId.Fac_GG_CutePho_Photo_IsA_TextImg9203,
		GG_CutePho_KinPhoGal_Belongs_Def = SetupVertexId.Fac_GG_CutePho_KinPhoGal_Belongs_Def,
		GG_CutePho_Receives_Favorite = SetupVertexId.Fac_GG_CutePho_Receives_Favorite,
		GG_CutePho_Photo_IsA_Focal = SetupVertexId.Fac_GG_CutePho_Photo_IsA_Focal,
		GZ_CutePho_Photo_IsA_Focal = SetupVertexId.Fac_GZ_CutePho_Photo_IsA_Focal,
		GM_CutePho_Photo_IsA_Focal = SetupVertexId.Fac_GM_CutePho_Photo_IsA_Focal,
		GG_CutePho_Photo_IsA_Expose = SetupVertexId.Fac_GG_CutePho_Photo_IsA_Expose,
		GG_CutePho_Photo_IsA_FStop = SetupVertexId.Fac_GG_CutePho_Photo_IsA_FStop,
		GG_CutePho_Photo_IsA_Iso = SetupVertexId.Fac_GG_CutePho_Photo_IsA_Iso,
		GG_CutePho_Photo_IsA_Quality = SetupVertexId.Fac_GG_CutePho_Photo_IsA_Quality,
		GM_CutePho_Ellie_Refers_Subject = SetupVertexId.Fac_GM_CutePho_Ellie_Refers_Subject,
		GM_CutePho_Smile_HasA_Subject = SetupVertexId.Fac_GM_CutePho_Smile_HasA_Subject,
		GM_CutePho_Pigtail_HasA_Subject = SetupVertexId.Fac_GM_CutePho_Pigtail_HasA_Subject,
		GM_CutePho_Rope_HasA_Object_Blue = SetupVertexId.Fac_GM_CutePho_Rope_HasA_Object_Blue,
		GM_CutePho_Swing_HasA_Object = SetupVertexId.Fac_GM_CutePho_Swing_HasA_Object,
		GZ_CutePho_Ellie_Refers_Subject = SetupVertexId.Fac_GZ_CutePho_Ellie_Refers_Subject,
		GZ_CutePho_Fisher_Refers_Object = SetupVertexId.Fac_GZ_CutePho_Fisher_Refers_Object,
		GZ_CutePho_Swing_Refers_Object = SetupVertexId.Fac_GZ_CutePho_Swing_Refers_Object,
		GM_CutePho_Happiness_Emotes = SetupVertexId.Fac_GM_CutePho_Happiness_Emotes,
		GM_CutePho_Fun_Emotes = SetupVertexId.Fac_GM_CutePho_Fun_Emotes,
		GZ_CutePho_Photo_IsA_Occur_QualityA = SetupVertexId.Fac_GZ_CutePho_Photo_IsA_Occur_QualityA,
		GZ_CutePho_Photo_IsA_Occur_QualityB = SetupVertexId.Fac_GZ_CutePho_Photo_IsA_Occur_QualityB,
		GZ_CutePho_Photo_IsA_Occur_QualityC = SetupVertexId.Fac_GZ_CutePho_Photo_IsA_Occur_QualityC,
		GM_CutePho_Photo_IsA_Occur_Quality = SetupVertexId.Fac_GM_CutePho_Photo_IsA_Occur_Quality,
		GZ_CutePho_Photo_IsA_Occur_Cuteness = SetupVertexId.Fac_GZ_CutePho_Photo_IsA_Occur_Cuteness,
		GM_CutePho_Photo_IsA_Occur_Cuteness = SetupVertexId.Fac_GM_CutePho_Photo_IsA_Occur_Cuteness,
		GE_CutePho_Photo_IsA_Occur_Cuteness = SetupVertexId.Fac_GE_CutePho_Photo_IsA_Occur_Cuteness,
	}

}