//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fabric.Api.Meta.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DtoLinkText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DtoLinkText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fabric.Api.Meta.Lang.DtoLinkText", typeof(DtoLinkText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idenfies membership status and access privileges..
        /// </summary>
        internal static string _Crowdian_CrowdianTypeKey {
            get {
                return ResourceManager.GetString("_Crowdian_CrowdianTypeKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links an App to a particular Member..
        /// </summary>
        internal static string AppDefinesMember {
            get {
                return ResourceManager.GetString("AppDefinesMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links an App to the Artifact that it owns..
        /// </summary>
        internal static string AppHasArtifact {
            get {
                return ResourceManager.GetString("AppHasArtifact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links an Artifact to an ArtifactType that describes the type of the associated ArtifactOwnerNode..
        /// </summary>
        internal static string ArtifactUsesArtifactType {
            get {
                return ResourceManager.GetString("ArtifactUsesArtifactType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links an App to the Class that it owns..
        /// </summary>
        internal static string ClassHasArtifact {
            get {
                return ResourceManager.GetString("ClassHasArtifact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links a Descriptor to an Artifact that specifies or clarifies a particular aspect of the Factor&apos;s primary Artifact..
        /// </summary>
        internal static string DescriptorRefinesPrimaryWithArtifact {
            get {
                return ResourceManager.GetString("DescriptorRefinesPrimaryWithArtifact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links a Descriptor to an Artifact that specifies or clarifies a particular aspect of the Factor&apos;s related Artifact..
        /// </summary>
        internal static string DescriptorRefinesRelatedWithArtifact {
            get {
                return ResourceManager.GetString("DescriptorRefinesRelatedWithArtifact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links a Descriptor to an Artifact that specifies or clarifies a particular aspect of the DescriptorType&apos;s meaning or purpose..
        /// </summary>
        internal static string DescriptorRefinesTypeWithArtifact {
            get {
                return ResourceManager.GetString("DescriptorRefinesTypeWithArtifact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links a Descriptor to a DescriptorType that specifies the type of relationship or connection..
        /// </summary>
        internal static string DescriptorUsesDescriptorType {
            get {
                return ResourceManager.GetString("DescriptorUsesDescriptorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links a Director to a DirectorType that specifies the type and reason for the pathway..
        /// </summary>
        internal static string DirectorUsesDirectorType {
            get {
                return ResourceManager.GetString("DirectorUsesDirectorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links a Director to a DirectorAction that specifies the action to be performed on the Factor&apos;s primary Artifact..
        /// </summary>
        internal static string DirectorUsesPrimaryDirectorAction {
            get {
                return ResourceManager.GetString("DirectorUsesPrimaryDirectorAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links a Director to a DirectorAction that specifies the action to be performed on the Factor&apos;s related Artifact..
        /// </summary>
        internal static string DirectorUsesRelatedDirectorAction {
            get {
                return ResourceManager.GetString("DirectorUsesRelatedDirectorAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links an Eventor to an EventorPrecision that specifies the level of accuracy given to this point in time..
        /// </summary>
        internal static string EventorUsesEventorPrecision {
            get {
                return ResourceManager.GetString("EventorUsesEventorPrecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links an Eventor to an EventorType that specifies the significance of this point in time..
        /// </summary>
        internal static string EventorUsesEventorType {
            get {
                return ResourceManager.GetString("EventorUsesEventorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links a new Factor to the Factor that it has replaced..
        /// </summary>
        internal static string FactorReplacesFactor {
            get {
                return ResourceManager.GetString("FactorReplacesFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links a Factor to its Descriptor Element, which defines the relationship between the primary and related Artifact..
        /// </summary>
        internal static string FactorUsesDescriptor {
            get {
                return ResourceManager.GetString("FactorUsesDescriptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links a Factor to its Director Element, which creates a directional pathway between the primary and related Artifacts..
        /// </summary>
        internal static string FactorUsesDirector {
            get {
                return ResourceManager.GetString("FactorUsesDirector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links a Factor to its Eventor Element, which applies the concept of time..
        /// </summary>
        internal static string FactorUsesEventor {
            get {
                return ResourceManager.GetString("FactorUsesEventor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links a Factor to a FactorAssertion that specifies the type of information and/or level of confidence..
        /// </summary>
        internal static string FactorUsesFactorAssertion {
            get {
                return ResourceManager.GetString("FactorUsesFactorAssertion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links a Factor to its Identor Element, which applies a name or identifier..
        /// </summary>
        internal static string FactorUsesIdentor {
            get {
                return ResourceManager.GetString("FactorUsesIdentor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links a Factor to its Locator Element, which provides a geographical or relative position..
        /// </summary>
        internal static string FactorUsesLocator {
            get {
                return ResourceManager.GetString("FactorUsesLocator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links a Factor to its primary Artifact, which represents the starting point of the Factor&apos;s directional Artifact relationship..
        /// </summary>
        internal static string FactorUsesPrimaryArtifact {
            get {
                return ResourceManager.GetString("FactorUsesPrimaryArtifact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links a Factor to its related Artifact, which represents the ending point of the Factor&apos;s directional Artifact relationship..
        /// </summary>
        internal static string FactorUsesRelatedArtifact {
            get {
                return ResourceManager.GetString("FactorUsesRelatedArtifact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links a Factor to its Vector Element, which applies a numeric axis and value..
        /// </summary>
        internal static string FactorUsesVector {
            get {
                return ResourceManager.GetString("FactorUsesVector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links an Identor to an IdentorType that specifies the value&apos;s purpose or intent..
        /// </summary>
        internal static string IdentorUsesIdentorType {
            get {
                return ResourceManager.GetString("IdentorUsesIdentorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links an App to the Instance that it owns..
        /// </summary>
        internal static string InstanceHasArtifact {
            get {
                return ResourceManager.GetString("InstanceHasArtifact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links a Locator to a LocatorType that specifies the spatial context of the coordinate..
        /// </summary>
        internal static string LocatorUsesLocatorType {
            get {
                return ResourceManager.GetString("LocatorUsesLocatorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links a Member to the Artifact that it created..
        /// </summary>
        internal static string MemberCreatesArtifact {
            get {
                return ResourceManager.GetString("MemberCreatesArtifact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links a Member to the Factor that it created..
        /// </summary>
        internal static string MemberCreatesFactor {
            get {
                return ResourceManager.GetString("MemberCreatesFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links a Member to the MemberTypeAssign that it created..
        /// </summary>
        internal static string MemberCreatesMemberTypeAssign {
            get {
                return ResourceManager.GetString("MemberCreatesMemberTypeAssign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links a Member to a historical MemberTypeAssign..
        /// </summary>
        internal static string MemberHasHistoricMemberTypeAssign {
            get {
                return ResourceManager.GetString("MemberHasHistoricMemberTypeAssign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links a Member to its active MemberTypeAssign..
        /// </summary>
        internal static string MemberHasMemberTypeAssign {
            get {
                return ResourceManager.GetString("MemberHasMemberTypeAssign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links a MemberTypeAssign to a MemberType that specifies the Member&apos;s state and/or access privileges..
        /// </summary>
        internal static string MemberTypeAssignUsesMemberType {
            get {
                return ResourceManager.GetString("MemberTypeAssignUsesMemberType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links the Root node to an App..
        /// </summary>
        internal static string RootContainsApp {
            get {
                return ResourceManager.GetString("RootContainsApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links the Root node to an Artifact..
        /// </summary>
        internal static string RootContainsArtifact {
            get {
                return ResourceManager.GetString("RootContainsArtifact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links the Root node to an ArtifactType..
        /// </summary>
        internal static string RootContainsArtifactType {
            get {
                return ResourceManager.GetString("RootContainsArtifactType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links the Root node to a Class..
        /// </summary>
        internal static string RootContainsClass {
            get {
                return ResourceManager.GetString("RootContainsClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links the Root node to a Descriptor..
        /// </summary>
        internal static string RootContainsDescriptor {
            get {
                return ResourceManager.GetString("RootContainsDescriptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links the Root node to a DescriptorType..
        /// </summary>
        internal static string RootContainsDescriptorType {
            get {
                return ResourceManager.GetString("RootContainsDescriptorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links the Root node to a Director..
        /// </summary>
        internal static string RootContainsDirector {
            get {
                return ResourceManager.GetString("RootContainsDirector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links the Root node to a DirectorAction..
        /// </summary>
        internal static string RootContainsDirectorAction {
            get {
                return ResourceManager.GetString("RootContainsDirectorAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links the Root node to a DirectorType..
        /// </summary>
        internal static string RootContainsDirectorType {
            get {
                return ResourceManager.GetString("RootContainsDirectorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links the Root node to an Eventor..
        /// </summary>
        internal static string RootContainsEventor {
            get {
                return ResourceManager.GetString("RootContainsEventor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links the Root node to an EventorPrecision..
        /// </summary>
        internal static string RootContainsEventorPrecision {
            get {
                return ResourceManager.GetString("RootContainsEventorPrecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links the Root node to an EventorType..
        /// </summary>
        internal static string RootContainsEventorType {
            get {
                return ResourceManager.GetString("RootContainsEventorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links the Root node to a Factor..
        /// </summary>
        internal static string RootContainsFactor {
            get {
                return ResourceManager.GetString("RootContainsFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links the Root node to a FactorAssertion..
        /// </summary>
        internal static string RootContainsFactorAssertion {
            get {
                return ResourceManager.GetString("RootContainsFactorAssertion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links the Root node to an Identor..
        /// </summary>
        internal static string RootContainsIdentor {
            get {
                return ResourceManager.GetString("RootContainsIdentor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links the Root node to an IdentorType..
        /// </summary>
        internal static string RootContainsIdentorType {
            get {
                return ResourceManager.GetString("RootContainsIdentorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links the Root node to an Instance..
        /// </summary>
        internal static string RootContainsInstance {
            get {
                return ResourceManager.GetString("RootContainsInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links the Root node to a Locator..
        /// </summary>
        internal static string RootContainsLocator {
            get {
                return ResourceManager.GetString("RootContainsLocator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links the Root node to a LocatorType..
        /// </summary>
        internal static string RootContainsLocatorType {
            get {
                return ResourceManager.GetString("RootContainsLocatorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links the Root node to a Member..
        /// </summary>
        internal static string RootContainsMember {
            get {
                return ResourceManager.GetString("RootContainsMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links the Root node to a MemberType..
        /// </summary>
        internal static string RootContainsMemberType {
            get {
                return ResourceManager.GetString("RootContainsMemberType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links the Root node to a MemberTypeAssign..
        /// </summary>
        internal static string RootContainsMemberTypeAssign {
            get {
                return ResourceManager.GetString("RootContainsMemberTypeAssign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links the Root node to a Url..
        /// </summary>
        internal static string RootContainsUrl {
            get {
                return ResourceManager.GetString("RootContainsUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links the Root node to a User..
        /// </summary>
        internal static string RootContainsUser {
            get {
                return ResourceManager.GetString("RootContainsUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links the Root node to a Vector..
        /// </summary>
        internal static string RootContainsVector {
            get {
                return ResourceManager.GetString("RootContainsVector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links the Root node to a VectorRange..
        /// </summary>
        internal static string RootContainsVectorRange {
            get {
                return ResourceManager.GetString("RootContainsVectorRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links the Root node to a VectorRangeLevel..
        /// </summary>
        internal static string RootContainsVectorRangeLevel {
            get {
                return ResourceManager.GetString("RootContainsVectorRangeLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links the Root node to a VectorType..
        /// </summary>
        internal static string RootContainsVectorType {
            get {
                return ResourceManager.GetString("RootContainsVectorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links the Root node to a VectorUnit..
        /// </summary>
        internal static string RootContainsVectorUnit {
            get {
                return ResourceManager.GetString("RootContainsVectorUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links the Root node to a VectorUnitDerived..
        /// </summary>
        internal static string RootContainsVectorUnitDerived {
            get {
                return ResourceManager.GetString("RootContainsVectorUnitDerived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links the Root node to a VectorUnitPrefix..
        /// </summary>
        internal static string RootContainsVectorUnitPrefix {
            get {
                return ResourceManager.GetString("RootContainsVectorUnitPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links a Url to the Artifact that it owns..
        /// </summary>
        internal static string UrlHasArtifact {
            get {
                return ResourceManager.GetString("UrlHasArtifact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links a User to a particular Member..
        /// </summary>
        internal static string UserDefinesMember {
            get {
                return ResourceManager.GetString("UserDefinesMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links a User to the Artifact that it owns..
        /// </summary>
        internal static string UserHasArtifact {
            get {
                return ResourceManager.GetString("UserHasArtifact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links a VectorRange to one of the VectorRangeLevels that help give it meaning..
        /// </summary>
        internal static string VectorRangeUsesVectorRangeLevel {
            get {
                return ResourceManager.GetString("VectorRangeUsesVectorRangeLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links a VectorType to a VectorRange that specifies a meaningful points/labels mapped to the numerical range..
        /// </summary>
        internal static string VectorTypeUsesVectorRange {
            get {
                return ResourceManager.GetString("VectorTypeUsesVectorRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        internal static string VectorUnitDerivedDefinesVectorUnit {
            get {
                return ResourceManager.GetString("VectorUnitDerivedDefinesVectorUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        internal static string VectorUnitDerivedRaisesToExpVectorUnit {
            get {
                return ResourceManager.GetString("VectorUnitDerivedRaisesToExpVectorUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        internal static string VectorUnitDerivedUsesVectorUnitPrefix {
            get {
                return ResourceManager.GetString("VectorUnitDerivedUsesVectorUnitPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links a Vector to an Artifact that &apos;labels&apos; its value&apos;s axis..
        /// </summary>
        internal static string VectorUsesAxisArtifact {
            get {
                return ResourceManager.GetString("VectorUsesAxisArtifact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links a Vector to a VectorType that specifies its value&apos;s boundaries and context..
        /// </summary>
        internal static string VectorUsesVectorType {
            get {
                return ResourceManager.GetString("VectorUsesVectorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links a Vector to a VectorUnit that specifies its value&apos;s unit of measurement..
        /// </summary>
        internal static string VectorUsesVectorUnit {
            get {
                return ResourceManager.GetString("VectorUsesVectorUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links a Vector to a VectorUnitPrefix that specifies its value&apos;s order of magnitude..
        /// </summary>
        internal static string VectorUsesVectorUnitPrefix {
            get {
                return ResourceManager.GetString("VectorUsesVectorUnitPrefix", resourceCulture);
            }
        }
    }
}
