//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fabric.Api.Meta.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DtoPropText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DtoPropText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fabric.Api.Meta.Lang.DtoPropText", typeof(DtoPropText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A unique title or identifier..
        /// </summary>
        internal static string App_Name {
            get {
                return ResourceManager.GetString("App_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date/time of creation..
        /// </summary>
        internal static string Artifact_Created {
            get {
                return ResourceManager.GetString("Artifact_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the accessibility level. When true, access is limited to the creating User..
        /// </summary>
        internal static string Artifact_IsPrivate {
            get {
                return ResourceManager.GetString("Artifact_IsPrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A decriptive (but non-unique) title, based on the name of the corresponding item..
        /// </summary>
        internal static string Artifact_Name {
            get {
                return ResourceManager.GetString("Artifact_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BatchNewClass_Disamb {
            get {
                return ResourceManager.GetString("BatchNewClass_Disamb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BatchNewClass_Name {
            get {
                return ResourceManager.GetString("BatchNewClass_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BatchNewClass_Note {
            get {
                return ResourceManager.GetString("BatchNewClass_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BatchNewFactor_Descriptor {
            get {
                return ResourceManager.GetString("BatchNewFactor_Descriptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BatchNewFactor_Director {
            get {
                return ResourceManager.GetString("BatchNewFactor_Director", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BatchNewFactor_Eventor {
            get {
                return ResourceManager.GetString("BatchNewFactor_Eventor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BatchNewFactor_FactorAssertionId {
            get {
                return ResourceManager.GetString("BatchNewFactor_FactorAssertionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BatchNewFactor_Identor {
            get {
                return ResourceManager.GetString("BatchNewFactor_Identor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BatchNewFactor_IsDefining {
            get {
                return ResourceManager.GetString("BatchNewFactor_IsDefining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BatchNewFactor_Locator {
            get {
                return ResourceManager.GetString("BatchNewFactor_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BatchNewFactor_Note {
            get {
                return ResourceManager.GetString("BatchNewFactor_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BatchNewFactor_PrimaryArtifactId {
            get {
                return ResourceManager.GetString("BatchNewFactor_PrimaryArtifactId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BatchNewFactor_RelatedArtifactId {
            get {
                return ResourceManager.GetString("BatchNewFactor_RelatedArtifactId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BatchNewFactor_Vector {
            get {
                return ResourceManager.GetString("BatchNewFactor_Vector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BatchNewFactorDescriptor_PrimaryArtifactRefineId {
            get {
                return ResourceManager.GetString("BatchNewFactorDescriptor_PrimaryArtifactRefineId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BatchNewFactorDescriptor_RelatedArtifactRefineId {
            get {
                return ResourceManager.GetString("BatchNewFactorDescriptor_RelatedArtifactRefineId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BatchNewFactorDescriptor_TypeId {
            get {
                return ResourceManager.GetString("BatchNewFactorDescriptor_TypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BatchNewFactorDescriptor_TypeRefineId {
            get {
                return ResourceManager.GetString("BatchNewFactorDescriptor_TypeRefineId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BatchNewFactorDirector_PrimaryActionId {
            get {
                return ResourceManager.GetString("BatchNewFactorDirector_PrimaryActionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BatchNewFactorDirector_RelatedActionId {
            get {
                return ResourceManager.GetString("BatchNewFactorDirector_RelatedActionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BatchNewFactorDirector_TypeId {
            get {
                return ResourceManager.GetString("BatchNewFactorDirector_TypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BatchNewFactorEventor_DateTime {
            get {
                return ResourceManager.GetString("BatchNewFactorEventor_DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BatchNewFactorEventor_PrecisionId {
            get {
                return ResourceManager.GetString("BatchNewFactorEventor_PrecisionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BatchNewFactorEventor_TypeId {
            get {
                return ResourceManager.GetString("BatchNewFactorEventor_TypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BatchNewFactorIdentor_TypeId {
            get {
                return ResourceManager.GetString("BatchNewFactorIdentor_TypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BatchNewFactorIdentor_Value {
            get {
                return ResourceManager.GetString("BatchNewFactorIdentor_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BatchNewFactorLocator_TypeId {
            get {
                return ResourceManager.GetString("BatchNewFactorLocator_TypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BatchNewFactorLocator_ValueX {
            get {
                return ResourceManager.GetString("BatchNewFactorLocator_ValueX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BatchNewFactorLocator_ValueY {
            get {
                return ResourceManager.GetString("BatchNewFactorLocator_ValueY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BatchNewFactorLocator_ValueZ {
            get {
                return ResourceManager.GetString("BatchNewFactorLocator_ValueZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BatchNewFactorVector_AxisArtifactId {
            get {
                return ResourceManager.GetString("BatchNewFactorVector_AxisArtifactId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BatchNewFactorVector_TypeId {
            get {
                return ResourceManager.GetString("BatchNewFactorVector_TypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BatchNewFactorVector_UnitId {
            get {
                return ResourceManager.GetString("BatchNewFactorVector_UnitId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BatchNewFactorVector_UnitPrefixId {
            get {
                return ResourceManager.GetString("BatchNewFactorVector_UnitPrefixId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BatchNewFactorVector_Value {
            get {
                return ResourceManager.GetString("BatchNewFactorVector_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        internal static string BatchNewObject_BatchId {
            get {
                return ResourceManager.GetString("BatchNewObject_BatchId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        internal static string BatchResult_BatchId {
            get {
                return ResourceManager.GetString("BatchResult_BatchId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        internal static string BatchResult_Error {
            get {
                return ResourceManager.GetString("BatchResult_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        internal static string BatchResult_ResultId {
            get {
                return ResourceManager.GetString("BatchResult_ResultId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A secondary label or identifier, used to resolve unique-name conflicts..
        /// </summary>
        internal static string Class_Disamb {
            get {
                return ResourceManager.GetString("Class_Disamb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A descriptive name or title..
        /// </summary>
        internal static string Class_Name {
            get {
                return ResourceManager.GetString("Class_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A summary of the !Class&apos;s intended meaning or purpose. This can resolve confusion in cases where a !Class has vague or missing Factors..
        /// </summary>
        internal static string Class_Note {
            get {
                return ResourceManager.GetString("Class_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A brief summary of purpose, usage, and/or guidelines..
        /// </summary>
        internal static string Crowd_Description {
            get {
                return ResourceManager.GetString("Crowd_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the membership requirement. Refer to an invite-only !Crowd as &apos;restricted&apos;. Otherwise, refer to it as &apos;open&apos;..
        /// </summary>
        internal static string Crowd_IsInviteOnly {
            get {
                return ResourceManager.GetString("Crowd_IsInviteOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the level of accessibility. A private !Crowd is called a &apos;Circle&apos;..
        /// </summary>
        internal static string Crowd_IsPrivate {
            get {
                return ResourceManager.GetString("Crowd_IsPrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A descriptive name or title..
        /// </summary>
        internal static string Crowd_Name {
            get {
                return ResourceManager.GetString("Crowd_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A value (between 0.0 and 1.0) which represents relative impact on Crowd-based data analysis. The default value is 0.5..
        /// </summary>
        internal static string CrowdianTypeAssign_Weight {
            get {
                return ResourceManager.GetString("CrowdianTypeAssign_Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the type of relationship or connection..
        /// </summary>
        internal static string Descriptor_TypeId {
            get {
                return ResourceManager.GetString("Descriptor_TypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the action to be performed on the Factor&apos;s primary Artifact..
        /// </summary>
        internal static string Director_PrimaryActionId {
            get {
                return ResourceManager.GetString("Director_PrimaryActionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the action to be performed on the Factor&apos;s related Artifact..
        /// </summary>
        internal static string Director_RelatedActionId {
            get {
                return ResourceManager.GetString("Director_RelatedActionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the type and reason for the pathway..
        /// </summary>
        internal static string Director_TypeId {
            get {
                return ResourceManager.GetString("Director_TypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A numeric value which identifies the specific error type..
        /// </summary>
        internal static string Error_Code {
            get {
                return ResourceManager.GetString("Error_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A sentence or paragraph providing details about the error..
        /// </summary>
        internal static string Error_Message {
            get {
                return ResourceManager.GetString("Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A descriptive name that is associated with the error code..
        /// </summary>
        internal static string Error_Name {
            get {
                return ResourceManager.GetString("Error_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A particular point in time, with a level of accuracy defined by EventorPrecision..
        /// </summary>
        internal static string Eventor_DateTime {
            get {
                return ResourceManager.GetString("Eventor_DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the level of accuracy given to this point in time..
        /// </summary>
        internal static string Eventor_PrecisionId {
            get {
                return ResourceManager.GetString("Eventor_PrecisionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the significance of this point in time..
        /// </summary>
        internal static string Eventor_TypeId {
            get {
                return ResourceManager.GetString("Eventor_TypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date/time of completion. This value is null if the !Factor is not complete..
        /// </summary>
        internal static string Factor_Completed {
            get {
                return ResourceManager.GetString("Factor_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date/time of creation..
        /// </summary>
        internal static string Factor_Created {
            get {
                return ResourceManager.GetString("Factor_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This element defines the relationship between the primary and related Artifact..
        /// </summary>
        internal static string Factor_Descriptor {
            get {
                return ResourceManager.GetString("Factor_Descriptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This element creates a directional pathway between the primary and related Artifacts..
        /// </summary>
        internal static string Factor_Director {
            get {
                return ResourceManager.GetString("Factor_Director", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This element applies the concept of time..
        /// </summary>
        internal static string Factor_Eventor {
            get {
                return ResourceManager.GetString("Factor_Eventor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the type of information and/or level of confidence..
        /// </summary>
        internal static string Factor_FactorAssertionId {
            get {
                return ResourceManager.GetString("Factor_FactorAssertionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This element applies a name or identifier..
        /// </summary>
        internal static string Factor_Identor {
            get {
                return ResourceManager.GetString("Factor_Identor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies whether this !Factor helps to directly and uniquely define the primary Artifact..
        /// </summary>
        internal static string Factor_IsDefining {
            get {
                return ResourceManager.GetString("Factor_IsDefining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the level of access..
        /// </summary>
        internal static string Factor_IsPublic {
            get {
                return ResourceManager.GetString("Factor_IsPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This element provides a geographical or relative position..
        /// </summary>
        internal static string Factor_Locator {
            get {
                return ResourceManager.GetString("Factor_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A summary of the !Factor&apos;s intended meaning or purpose. This is useful in cases when the !Factor is vague, complex, or confusing. It can help resolve issues in cases where the Factor&apos;s Elements inaccurately model the intended meaning. Typically, this value is not written directly by a User; the App should have enough information about a particular !Factor-creating action to form a reasonable sentence or phrase..
        /// </summary>
        internal static string Factor_Note {
            get {
                return ResourceManager.GetString("Factor_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This element applies a numeric axis and value..
        /// </summary>
        internal static string Factor_Vector {
            get {
                return ResourceManager.GetString("Factor_Vector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information about the details and/or causes of the Fault..
        /// </summary>
        internal static string Fault_Message {
            get {
                return ResourceManager.GetString("Fault_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The complete list of services..
        /// </summary>
        internal static string Home_Services {
            get {
                return ResourceManager.GetString("Home_Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the value&apos;s purpose or intent..
        /// </summary>
        internal static string Identor_TypeId {
            get {
                return ResourceManager.GetString("Identor_TypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A text-based value that can represent names, numbers, IDs, GUIDs, etc..
        /// </summary>
        internal static string Identor_Value {
            get {
                return ResourceManager.GetString("Identor_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A secondary label or identifier, used to resolve unique-name conflicts..
        /// </summary>
        internal static string Instance_Disamb {
            get {
                return ResourceManager.GetString("Instance_Disamb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A descriptive name or title..
        /// </summary>
        internal static string Instance_Name {
            get {
                return ResourceManager.GetString("Instance_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A summary of the !Instance&apos;s intended meaning or purpose. This can resolve confusion in cases where an !Instance has vague or missing Factors..
        /// </summary>
        internal static string Instance_Note {
            get {
                return ResourceManager.GetString("Instance_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifies a particular object..
        /// </summary>
        internal static string Key_Id {
            get {
                return ResourceManager.GetString("Key_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The API path to get information about this Key&apos;s object..
        /// </summary>
        internal static string Key_Uri {
            get {
                return ResourceManager.GetString("Key_Uri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A unique title or identifier..
        /// </summary>
        internal static string Label_Name {
            get {
                return ResourceManager.GetString("Label_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the spatial context of the coordinate..
        /// </summary>
        internal static string Locator_TypeId {
            get {
                return ResourceManager.GetString("Locator_TypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A value representing longitude, time/progress, width, or a particular three-dimensional axis..
        /// </summary>
        internal static string Locator_ValueX {
            get {
                return ResourceManager.GetString("Locator_ValueX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A value representing latitude, height, or a particular three-dimensional axis..
        /// </summary>
        internal static string Locator_ValueY {
            get {
                return ResourceManager.GetString("Locator_ValueY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A value representing elevation or a particular three-dimensional axis..
        /// </summary>
        internal static string Locator_ValueZ {
            get {
                return ResourceManager.GetString("Locator_ValueZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the Member&apos;s state and/or access privileges..
        /// </summary>
        internal static string MemberTypeAssign_MemberTypeId {
            get {
                return ResourceManager.GetString("MemberTypeAssign_MemberTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current day of the month..
        /// </summary>
        internal static string MetaTime_Day {
            get {
                return ResourceManager.GetString("MetaTime_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current hour (using 24-hour time)..
        /// </summary>
        internal static string MetaTime_Hour {
            get {
                return ResourceManager.GetString("MetaTime_Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current millisecond..
        /// </summary>
        internal static string MetaTime_Millisecond {
            get {
                return ResourceManager.GetString("MetaTime_Millisecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current minute..
        /// </summary>
        internal static string MetaTime_Minute {
            get {
                return ResourceManager.GetString("MetaTime_Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current month..
        /// </summary>
        internal static string MetaTime_Month {
            get {
                return ResourceManager.GetString("MetaTime_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current second..
        /// </summary>
        internal static string MetaTime_Second {
            get {
                return ResourceManager.GetString("MetaTime_Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current number of Ticks since January 1, 0001.  A Tick is one ten-millionth of a second; there are 10,000 Ticks per millisecond..
        /// </summary>
        internal static string MetaTime_Ticks {
            get {
                return ResourceManager.GetString("MetaTime_Ticks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Unix timestamp value, derived from the Ticks value..
        /// </summary>
        internal static string MetaTime_Unix {
            get {
                return ResourceManager.GetString("MetaTime_Unix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current year..
        /// </summary>
        internal static string MetaTime_Year {
            get {
                return ResourceManager.GetString("MetaTime_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The day of the month that this build was released..
        /// </summary>
        internal static string MetaVersion_Day {
            get {
                return ResourceManager.GetString("MetaVersion_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The major revision number for this build. This value is only incremented in cases where significant or important changes have occurred. These changes may introduce backwards-incompatability with previous builds..
        /// </summary>
        internal static string MetaVersion_Major {
            get {
                return ResourceManager.GetString("MetaVersion_Major", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minor revision number for this build. This value is incremented in cases when substantial functionality or improvements are introduced. It may also occur when certain functionality becomes deprecated..
        /// </summary>
        internal static string MetaVersion_Minor {
            get {
                return ResourceManager.GetString("MetaVersion_Minor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The month that this build was released..
        /// </summary>
        internal static string MetaVersion_Month {
            get {
                return ResourceManager.GetString("MetaVersion_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The patch revision number for this build. This value is incremented when bug fixes or other internal changes occur..
        /// </summary>
        internal static string MetaVersion_Patch {
            get {
                return ResourceManager.GetString("MetaVersion_Patch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The revision text is derived from internal build information. It may be safely omitted from the build&apos;s version string..
        /// </summary>
        internal static string MetaVersion_Revision {
            get {
                return ResourceManager.GetString("MetaVersion_Revision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This build&apos;s full version string, in the format: &quot;Major.Minor.Patch.Revision&quot;..
        /// </summary>
        internal static string MetaVersion_Version {
            get {
                return ResourceManager.GetString("MetaVersion_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The year that this build was released..
        /// </summary>
        internal static string MetaVersion_Year {
            get {
                return ResourceManager.GetString("MetaVersion_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Append this value to the current URI to filter down to this specific Vertex in current traversal path..
        /// </summary>
        internal static string Vertex_Uri {
            get {
                return ResourceManager.GetString("Vertex_Uri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A brief note describing this action..
        /// </summary>
        internal static string VertexForAction_Note {
            get {
                return ResourceManager.GetString("VertexForAction_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date/time this action was performed..
        /// </summary>
        internal static string VertexForAction_Performed {
            get {
                return ResourceManager.GetString("VertexForAction_Performed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A code that maps to various authentication information. Notably, it is refers to exactly one App and at most one User..
        /// </summary>
        internal static string OauthAccess_AccessToken {
            get {
                return ResourceManager.GetString("OauthAccess_AccessToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of seconds until the access token expires..
        /// </summary>
        internal static string OauthAccess_ExpiresIn {
            get {
                return ResourceManager.GetString("OauthAccess_ExpiresIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A code that refreshes the authentication session for an expired OAuth access token. App-only access tokens do not include a refresh token; instead, the App should [[request a new access token|Oper|Oauth.AccessTokenClientCredentials]]..
        /// </summary>
        internal static string OauthAccess_RefreshToken {
            get {
                return ResourceManager.GetString("OauthAccess_RefreshToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For the current Fabric OAuth implementation, this value is always equal to &quot;bearer&quot;..
        /// </summary>
        internal static string OauthAccess_TokenType {
            get {
                return ResourceManager.GetString("OauthAccess_TokenType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error code as defined by the OAuth 2.0 specification..
        /// </summary>
        internal static string OauthError_Error {
            get {
                return ResourceManager.GetString("OauthError_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provides specific details about the error. A single error code may have one or more possible error descriptions..
        /// </summary>
        internal static string OauthError_ErrorDesc {
            get {
                return ResourceManager.GetString("OauthError_ErrorDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this code (also called the &apos;authorization code&apos;) to generate a new OAuth access token. For security purposes, each code is valid for a single use, and expires 120 seconds after creation..
        /// </summary>
        internal static string OauthLogin_Code {
            get {
                return ResourceManager.GetString("OauthLogin_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error code as defined by the OAuth 2.0 specification..
        /// </summary>
        internal static string OauthLogin_Error {
            get {
                return ResourceManager.GetString("OauthLogin_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provides specific details about the error. A single error code may have one or more possible error descriptions. For use in the redirect URI, this string uses a &apos;+&apos; character in place of each space character..
        /// </summary>
        internal static string OauthLogin_ErrorDesc {
            get {
                return ResourceManager.GetString("OauthLogin_ErrorDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the &apos;state&apos; value that the App provided in the original Oauth request. For security reasons, the App should reject the response if the original and returned values are not equal..
        /// </summary>
        internal static string OauthLogin_State {
            get {
                return ResourceManager.GetString("OauthLogin_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifies a particular OAuth session..
        /// </summary>
        internal static string OauthLogout_AccessToken {
            get {
                return ResourceManager.GetString("OauthLogout_AccessToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Describes the result of the logout attempt. Successful logout attempts return a value of 1..
        /// </summary>
        internal static string OauthLogout_Success {
            get {
                return ResourceManager.GetString("OauthLogout_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data type of this object..
        /// </summary>
        internal static string Object_FabType {
            get {
                return ResourceManager.GetString("Object_FabType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uniquely identifies this object amongst all other objects of this type..
        /// </summary>
        internal static string Object_TypeId {
            get {
                return ResourceManager.GetString("Object_TypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If an authenticated Member made this request, this identifies the App associated with that Member..
        /// </summary>
        internal static string Response_AppId {
            get {
                return ResourceManager.GetString("Response_AppId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The base URI for the Fabric API..
        /// </summary>
        internal static string Response_BaseUri {
            get {
                return ResourceManager.GetString("Response_BaseUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of results in the returned Data list..
        /// </summary>
        internal static string Response_Count {
            get {
                return ResourceManager.GetString("Response_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains the result of the request as a list of zero or more Objects..
        /// </summary>
        internal static string Response_Data {
            get {
                return ResourceManager.GetString("Response_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of characters in the JSON representation of the Data list..
        /// </summary>
        internal static string Response_DataLen {
            get {
                return ResourceManager.GetString("Response_DataLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The time (in milliseconds) that it took the database server(s) to complete all data requests..
        /// </summary>
        internal static string Response_DbMs {
            get {
                return ResourceManager.GetString("Response_DbMs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If an error occurred, this contains information about the problem. Typically, the Data value is null when an Error value is present..
        /// </summary>
        internal static string Response_Error {
            get {
                return ResourceManager.GetString("Response_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The traversal functions available for the current vertex list. This property is only used for [[Traversal Service|Serv|Traversal]] requests..
        /// </summary>
        internal static string Response_Functions {
            get {
                return ResourceManager.GetString("Response_Functions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates whether there are more verts available beyond the returned vertex list. This property is only used for [[Traversal Service|Serv|Traversal]] requests..
        /// </summary>
        internal static string Response_HasMore {
            get {
                return ResourceManager.GetString("Response_HasMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The HTTP status returned by this request..
        /// </summary>
        internal static string Response_HttpStatus {
            get {
                return ResourceManager.GetString("Response_HttpStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The traversal links available for the current vertex list. This property is only used for [[Traversal Service|Serv|Traversal]] requests..
        /// </summary>
        internal static string Response_Links {
            get {
                return ResourceManager.GetString("Response_Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URI of the current request..
        /// </summary>
        internal static string Response_RequestUri {
            get {
                return ResourceManager.GetString("Response_RequestUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The starting index of the returned vertex list. This property is only used for [[Traversal Service|Serv|Traversal]] requests..
        /// </summary>
        internal static string Response_StartIndex {
            get {
                return ResourceManager.GetString("Response_StartIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date/time of the current request..
        /// </summary>
        internal static string Response_Timestamp {
            get {
                return ResourceManager.GetString("Response_Timestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The time (in milliseconds) that it took the server(s) to complete this request..
        /// </summary>
        internal static string Response_TotalMs {
            get {
                return ResourceManager.GetString("Response_TotalMs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If an authenticated Member made this request, this identifies the User associated with that Member..
        /// </summary>
        internal static string Response_UserId {
            get {
                return ResourceManager.GetString("Response_UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service name..
        /// </summary>
        internal static string Service_Name {
            get {
                return ResourceManager.GetString("Service_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The complete list of operations for this service..
        /// </summary>
        internal static string Service_Operations {
            get {
                return ResourceManager.GetString("Service_Operations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Append this path to the current URI to obtain details about this service..
        /// </summary>
        internal static string Service_Uri {
            get {
                return ResourceManager.GetString("Service_Uri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The required HTTP method..
        /// </summary>
        internal static string ServiceOperation_Method {
            get {
                return ResourceManager.GetString("ServiceOperation_Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A descriptive name for this operation..
        /// </summary>
        internal static string ServiceOperation_Name {
            get {
                return ResourceManager.GetString("ServiceOperation_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of Object returned by this operation..
        /// </summary>
        internal static string ServiceOperation_ReturnType {
            get {
                return ResourceManager.GetString("ServiceOperation_ReturnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Append this value to the current URI (and use the correct HTTP method) to invoke this operation..
        /// </summary>
        internal static string ServiceOperation_Uri {
            get {
                return ResourceManager.GetString("ServiceOperation_Uri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Vertex type returned by the opposite end of this link..
        /// </summary>
        internal static string StepLink_Class {
            get {
                return ResourceManager.GetString("StepLink_Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates whether this link is outgoing (starting from the current Vertex) or incoming (starting from another Vertex)..
        /// </summary>
        internal static string StepLink_IsOut {
            get {
                return ResourceManager.GetString("StepLink_IsOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The relation type of this link..
        /// </summary>
        internal static string StepLink_Rel {
            get {
                return ResourceManager.GetString("StepLink_Rel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Append this value to the current URI to add this link to the traversal path..
        /// </summary>
        internal static string StepLink_Uri {
            get {
                return ResourceManager.GetString("StepLink_Uri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A unique, valid absolute URL. The string must include the link&apos;s protocol (such as &apos;http://&apos;)..
        /// </summary>
        internal static string Url_AbsoluteUrl {
            get {
                return ResourceManager.GetString("Url_AbsoluteUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A descriptive name or title..
        /// </summary>
        internal static string Url_Name {
            get {
                return ResourceManager.GetString("Url_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A unique username..
        /// </summary>
        internal static string User_Name {
            get {
                return ResourceManager.GetString("User_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies its value&apos;s boundaries and context..
        /// </summary>
        internal static string Vector_TypeId {
            get {
                return ResourceManager.GetString("Vector_TypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies its value&apos;s unit of measurement..
        /// </summary>
        internal static string Vector_UnitId {
            get {
                return ResourceManager.GetString("Vector_UnitId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies its value&apos;s order of magnitude..
        /// </summary>
        internal static string Vector_UnitPrefixId {
            get {
                return ResourceManager.GetString("Vector_UnitPrefixId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An integral value which is to be plotted along the specified axis. This value must account for the choice of prefix. After being multiplied by the prefix magnitude, the value must fall within the bounds specified by VectorType. Before prefix multiplication, this value must be between –9,223,372,036,854,775,808 and 9,223,372,036,854,775,807..
        /// </summary>
        internal static string Vector_Value {
            get {
                return ResourceManager.GetString("Vector_Value", resourceCulture);
            }
        }
    }
}
