//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fabric.Api.Meta.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EnumPropText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnumPropText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fabric.Api.Meta.Lang.EnumPropText", typeof(EnumPropText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A summary of this object&apos;s intended meaning or purpose..
        /// </summary>
        internal static string BaseEnum_Description {
            get {
                return ResourceManager.GetString("BaseEnum_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A unique string (with no spaces) that can be used by Fabric clients when creating an enumeration..
        /// </summary>
        internal static string BaseEnum_EnumId {
            get {
                return ResourceManager.GetString("BaseEnum_EnumId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The numeric identifier for this enumeration item..
        /// </summary>
        internal static string BaseEnum_Id {
            get {
                return ResourceManager.GetString("BaseEnum_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A descriptive name or title..
        /// </summary>
        internal static string BaseEnum_Name {
            get {
                return ResourceManager.GetString("BaseEnum_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum Locator X-coordinate value..
        /// </summary>
        internal static string LocatorType_MaxX {
            get {
                return ResourceManager.GetString("LocatorType_MaxX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum Locator Y-coordinate value..
        /// </summary>
        internal static string LocatorType_MaxY {
            get {
                return ResourceManager.GetString("LocatorType_MaxY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum Locator Z-coordinate value..
        /// </summary>
        internal static string LocatorType_MaxZ {
            get {
                return ResourceManager.GetString("LocatorType_MaxZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum Locator X-coordinate value..
        /// </summary>
        internal static string LocatorType_MinX {
            get {
                return ResourceManager.GetString("LocatorType_MinX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum Locator Y-coordinate value..
        /// </summary>
        internal static string LocatorType_MinY {
            get {
                return ResourceManager.GetString("LocatorType_MinY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum Locator Z-coordinate value..
        /// </summary>
        internal static string LocatorType_MinZ {
            get {
                return ResourceManager.GetString("LocatorType_MinZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The set of points/labels that describe a numerical range..
        /// </summary>
        internal static string VectorRange_VectorRangeLevelIds {
            get {
                return ResourceManager.GetString("VectorRange_VectorRangeLevelIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A value (between 0.0 and 1.0) which defines the relative position between a numeric range&apos;s minimum and maximum boundaries..
        /// </summary>
        internal static string VectorRangeLevel_Position {
            get {
                return ResourceManager.GetString("VectorRangeLevel_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum Vector value allowed..
        /// </summary>
        internal static string VectorType_Max {
            get {
                return ResourceManager.GetString("VectorType_Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum Vector value allowed..
        /// </summary>
        internal static string VectorType_Min {
            get {
                return ResourceManager.GetString("VectorType_Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies a meaningful points/labels mapped to the numerical range..
        /// </summary>
        internal static string VectorType_VectorRangeId {
            get {
                return ResourceManager.GetString("VectorType_VectorRangeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A unique symbol or abbreviation..
        /// </summary>
        internal static string VectorUnit_Symbol {
            get {
                return ResourceManager.GetString("VectorUnit_Symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more VectorUnitDerived items are used to represent a conversion into this particular [[unit|Enum|VectorUnit]]..
        /// </summary>
        internal static string VectorUnitDerived_DefinesVectorUnitId {
            get {
                return ResourceManager.GetString("VectorUnitDerived_DefinesVectorUnitId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The [[unit|Enum|VectorUnit]] for this particular item..
        /// </summary>
        internal static string VectorUnitDerived_RaisesVectorUnitId {
            get {
                return ResourceManager.GetString("VectorUnitDerived_RaisesVectorUnitId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The [[unit prefix|Enum|VectorUnitPrefix]] that affects the &quot;raises&quot; unit..
        /// </summary>
        internal static string VectorUnitDerived_RaisesVectorUnitPrefixId {
            get {
                return ResourceManager.GetString("VectorUnitDerived_RaisesVectorUnitPrefixId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The exponent that affects the &quot;raises&quot; unit..
        /// </summary>
        internal static string VectorUnitDerived_WithExponent {
            get {
                return ResourceManager.GetString("VectorUnitDerived_WithExponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The difference in magnitude (a multipler) relative to the base unit..
        /// </summary>
        internal static string VectorUnitPrefix_Amount {
            get {
                return ResourceManager.GetString("VectorUnitPrefix_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An abbreviation, which is typically placed directly before the VectorUnit symbol..
        /// </summary>
        internal static string VectorUnitPrefix_Symbol {
            get {
                return ResourceManager.GetString("VectorUnitPrefix_Symbol", resourceCulture);
            }
        }
    }
}
