//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fabric.Api.Meta.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FuncParamText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FuncParamText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fabric.Api.Meta.Lang.FuncParamText", typeof(FuncParamText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ArtifactId of the target App..
        /// </summary>
        internal static string AppId_Value {
            get {
                return ResourceManager.GetString("AppId_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        internal static string AppName_Value {
            get {
                return ResourceManager.GetString("AppName_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        internal static string AppNameContains_Tokens {
            get {
                return ResourceManager.GetString("AppNameContains_Tokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        internal static string ArtifactCreated_Operation {
            get {
                return ResourceManager.GetString("ArtifactCreated_Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        internal static string ArtifactCreated_Value {
            get {
                return ResourceManager.GetString("ArtifactCreated_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ArtifactId of the target Artifact..
        /// </summary>
        internal static string ArtifactId_Value {
            get {
                return ResourceManager.GetString("ArtifactId_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A named alias, which represents a particular place in the traversal path. This value must be unique across all other aliases in the traversal path..
        /// </summary>
        internal static string As_Alias {
            get {
                return ResourceManager.GetString("As_Alias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target named alias, which was defined by an [[As|Func|As]] function earlier in the traversal path..
        /// </summary>
        internal static string Back_Alias {
            get {
                return ResourceManager.GetString("Back_Alias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        internal static string ClassDisambContains_Tokens {
            get {
                return ResourceManager.GetString("ClassDisambContains_Tokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ArtifactId of the target Class..
        /// </summary>
        internal static string ClassId_Value {
            get {
                return ResourceManager.GetString("ClassId_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        internal static string ClassName_Value {
            get {
                return ResourceManager.GetString("ClassName_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        internal static string ClassNameContains_Tokens {
            get {
                return ResourceManager.GetString("ClassNameContains_Tokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        internal static string FactorCreated_Operation {
            get {
                return ResourceManager.GetString("FactorCreated_Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        internal static string FactorCreated_Value {
            get {
                return ResourceManager.GetString("FactorCreated_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The FactorId of the target Factor..
        /// </summary>
        internal static string FactorId_Value {
            get {
                return ResourceManager.GetString("FactorId_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        internal static string FactorIdentorValue_Value {
            get {
                return ResourceManager.GetString("FactorIdentorValue_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        internal static string FactorIdentorValueContains_Tokens {
            get {
                return ResourceManager.GetString("FactorIdentorValueContains_Tokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target vertex Id..
        /// </summary>
        internal static string HasId_Id {
            get {
                return ResourceManager.GetString("HasId_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        internal static string InstanceDisambContains_Tokens {
            get {
                return ResourceManager.GetString("InstanceDisambContains_Tokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ArtifactId of the target Instance..
        /// </summary>
        internal static string InstanceId_Value {
            get {
                return ResourceManager.GetString("InstanceId_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        internal static string InstanceNameContains_Tokens {
            get {
                return ResourceManager.GetString("InstanceNameContains_Tokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum number of verts to return..
        /// </summary>
        internal static string Limit_Count {
            get {
                return ResourceManager.GetString("Limit_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The starting index for the returned list of verts..
        /// </summary>
        internal static string Limit_Index {
            get {
                return ResourceManager.GetString("Limit_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MemberId of the target Member..
        /// </summary>
        internal static string MemberId_Value {
            get {
                return ResourceManager.GetString("MemberId_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MemberTypeAssignId of the target MemberTypeAssign..
        /// </summary>
        internal static string MemberTypeAssignId_Value {
            get {
                return ResourceManager.GetString("MemberTypeAssignId_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        internal static string UrlFullPath_Value {
            get {
                return ResourceManager.GetString("UrlFullPath_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The UrlId of the target Url..
        /// </summary>
        internal static string UrlId_Value {
            get {
                return ResourceManager.GetString("UrlId_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        internal static string UrlNameContains_Tokens {
            get {
                return ResourceManager.GetString("UrlNameContains_Tokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The UserId of the target User..
        /// </summary>
        internal static string UserId_Value {
            get {
                return ResourceManager.GetString("UserId_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        internal static string UserName_Value {
            get {
                return ResourceManager.GetString("UserName_Value", resourceCulture);
            }
        }
    }
}
