//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fabric.Api.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StepParamText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StepParamText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fabric.Api.Lang.StepParamText", typeof(StepParamText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A named alias, which represents a particular place in the traversal path. This value must be unique across all other aliases in the traversal path..
        /// </summary>
        internal static string As_Alias {
            get {
                return ResourceManager.GetString("As_Alias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target named alias, which was defined by an [[As|Func|As]] function earlier in the traversal path..
        /// </summary>
        internal static string Back_Alias {
            get {
                return ResourceManager.GetString("Back_Alias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum number of elements to return..
        /// </summary>
        internal static string Take_Count {
            get {
                return ResourceManager.GetString("Take_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operator that defines the type of range to use for this search. Options include: &quot;Greater Than&quot;, &quot;Less Than or Equal&quot;, &quot;Not Equal&quot;, etc..
        /// </summary>
        internal static string Where_Operation {
            get {
                return ResourceManager.GetString("Where_Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The boundary value for the search range..
        /// </summary>
        internal static string Where_Value {
            get {
                return ResourceManager.GetString("Where_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The space-delimited, case-insensitive search tokens..
        /// </summary>
        internal static string WhereContains_Tokens {
            get {
                return ResourceManager.GetString("WhereContains_Tokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        internal static string WhereEventorDateTime_Day {
            get {
                return ResourceManager.GetString("WhereEventorDateTime_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        internal static string WhereEventorDateTime_Hour {
            get {
                return ResourceManager.GetString("WhereEventorDateTime_Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        internal static string WhereEventorDateTime_Minute {
            get {
                return ResourceManager.GetString("WhereEventorDateTime_Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        internal static string WhereEventorDateTime_Month {
            get {
                return ResourceManager.GetString("WhereEventorDateTime_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        internal static string WhereEventorDateTime_Operation {
            get {
                return ResourceManager.GetString("WhereEventorDateTime_Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        internal static string WhereEventorDateTime_Second {
            get {
                return ResourceManager.GetString("WhereEventorDateTime_Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        internal static string WhereEventorDateTime_Year {
            get {
                return ResourceManager.GetString("WhereEventorDateTime_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The exact value to match for this search..
        /// </summary>
        internal static string With_Value {
            get {
                return ResourceManager.GetString("With_Value", resourceCulture);
            }
        }
    }
}
