//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fabric.Api.Spec.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DtoPropText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DtoPropText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fabric.Api.Spec.Lang.DtoPropText", typeof(DtoPropText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A unique title or identifier, with length between 3 and 64 characters. This string is restricted to the [[Title character set|Note|TitleCharSet]]..
        /// </summary>
        internal static string App_Name {
            get {
                return ResourceManager.GetString("App_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifies the associated object type, such as User or Thing..
        /// </summary>
        internal static string Artifact_ArtifactTypeKey {
            get {
                return ResourceManager.GetString("Artifact_ArtifactTypeKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date/time of creation..
        /// </summary>
        internal static string Artifact_Created {
            get {
                return ResourceManager.GetString("Artifact_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the accessibility level. When true, access is limited to the creating User..
        /// </summary>
        internal static string Artifact_IsPrivate {
            get {
                return ResourceManager.GetString("Artifact_IsPrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies whether new Threads and Comments are permitted..
        /// </summary>
        internal static string Artifact_IsTalkClosed {
            get {
                return ResourceManager.GetString("Artifact_IsTalkClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A decriptive (but non-unique) title, based on the name of the corresponding item..
        /// </summary>
        internal static string Artifact_Name {
            get {
                return ResourceManager.GetString("Artifact_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifies the corresponding {{Item}}, if applicable..
        /// </summary>
        internal static string Artifact_OfItem {
            get {
                return ResourceManager.GetString("Artifact_OfItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifies the associated {{Item}}..
        /// </summary>
        internal static string Common_AssociatedItem {
            get {
                return ResourceManager.GetString("Common_AssociatedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A brief summary of purpose, usage, and/or guidelines. Maximum length: {{Max}} characters..
        /// </summary>
        internal static string Common_Description {
            get {
                return ResourceManager.GetString("Common_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifies the Artifact that is associated exclusively with this {{Item}}..
        /// </summary>
        internal static string Common_ItemArtifactKey {
            get {
                return ResourceManager.GetString("Common_ItemArtifactKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifies the Member, User, and App responsible for the creation of this {{Item}}..
        /// </summary>
        internal static string Common_ItemCreator {
            get {
                return ResourceManager.GetString("Common_ItemCreator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A descriptive name or title. Maximum length: {{Max}} characters..
        /// </summary>
        internal static string Common_Name {
            get {
                return ResourceManager.GetString("Common_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date/time of the latest update..
        /// </summary>
        internal static string Common_Update {
            get {
                return ResourceManager.GetString("Common_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A brief summary of purpose, usage, and/or guidelines..
        /// </summary>
        internal static string Crowd_Description {
            get {
                return ResourceManager.GetString("Crowd_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the membership requirement. Refer to an invite-only !Crowd as &apos;restricted&apos;. Otherwise, refer to it as &apos;open&apos;..
        /// </summary>
        internal static string Crowd_IsInviteOnly {
            get {
                return ResourceManager.GetString("Crowd_IsInviteOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the level of accessibility. A private !Crowd is called a &apos;Circle&apos;..
        /// </summary>
        internal static string Crowd_IsPrivate {
            get {
                return ResourceManager.GetString("Crowd_IsPrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A descriptive name or title..
        /// </summary>
        internal static string Crowd_Name {
            get {
                return ResourceManager.GetString("Crowd_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idenfies membership status and access privileges..
        /// </summary>
        internal static string Crowdian_CrowdianTypeKey {
            get {
                return ResourceManager.GetString("Crowdian_CrowdianTypeKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A value (between 0.0 and 1.0) which represents relative impact on Crowd-based data analysis. The default value is 0.5..
        /// </summary>
        internal static string CrowdianTypeAssign_Weight {
            get {
                return ResourceManager.GetString("CrowdianTypeAssign_Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifies the type of relationship or connection..
        /// </summary>
        internal static string Descriptor_DescriptorTypeKey {
            get {
                return ResourceManager.GetString("Descriptor_DescriptorTypeKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifies a particular Artifact; this specifies or clarifies a particular aspect of the Factor&apos;s primary Artifact..
        /// </summary>
        internal static string Descriptor_RefinePrimaryWithArtifactKey {
            get {
                return ResourceManager.GetString("Descriptor_RefinePrimaryWithArtifactKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifies a particular Artifact; this specifies or clarifies a particular aspect of the Factor&apos;s related Artifact..
        /// </summary>
        internal static string Descriptor_RefineRelatedWithArtifactKey {
            get {
                return ResourceManager.GetString("Descriptor_RefineRelatedWithArtifactKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifies a particular Artifact; this specifies or clarifies the DescriptorType&apos;s meaning or purpose..
        /// </summary>
        internal static string Descriptor_RefineTypeWithArtifactKey {
            get {
                return ResourceManager.GetString("Descriptor_RefineTypeWithArtifactKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifies the type and reason for the pathway..
        /// </summary>
        internal static string Director_DirectorTypeKy {
            get {
                return ResourceManager.GetString("Director_DirectorTypeKy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifies the action to be performed on the Factor&apos;s primary Artifact..
        /// </summary>
        internal static string Director_PrimaryActionKey {
            get {
                return ResourceManager.GetString("Director_PrimaryActionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifies the action to be performed on the Factor&apos;s related Artifact..
        /// </summary>
        internal static string Director_RelatedActionKey {
            get {
                return ResourceManager.GetString("Director_RelatedActionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional information about the error..
        /// </summary>
        internal static string Error_Description {
            get {
                return ResourceManager.GetString("Error_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A descriptive name of the error or fault that occurred..
        /// </summary>
        internal static string Error_Name {
            get {
                return ResourceManager.GetString("Error_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A 3-digit numeric value which is also returned as the status code of the HTTP response..
        /// </summary>
        internal static string Error_StatusCode {
            get {
                return ResourceManager.GetString("Error_StatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A particular point in time, with a level of accuracy defined by EventorPrecision..
        /// </summary>
        internal static string Eventor_DateTime {
            get {
                return ResourceManager.GetString("Eventor_DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifies the level of accuracy given to this point in time..
        /// </summary>
        internal static string Eventor_EventorPrecisionKey {
            get {
                return ResourceManager.GetString("Eventor_EventorPrecisionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifies the significance of this point in time..
        /// </summary>
        internal static string Eventor_EventorTypeKey {
            get {
                return ResourceManager.GetString("Eventor_EventorTypeKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date/time of completion. This value is null if the !Factor is not complete..
        /// </summary>
        internal static string Factor_Completed {
            get {
                return ResourceManager.GetString("Factor_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date/time of creation..
        /// </summary>
        internal static string Factor_Created {
            get {
                return ResourceManager.GetString("Factor_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifies the Descriptor Element, which defines the relationship between the primary and related Artifact..
        /// </summary>
        internal static string Factor_DescriptorKey {
            get {
                return ResourceManager.GetString("Factor_DescriptorKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifies the Director Element, which creates a directional pathway between the primary and related Artifacts..
        /// </summary>
        internal static string Factor_DirectorKey {
            get {
                return ResourceManager.GetString("Factor_DirectorKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifies the Eventor Element, which applies the concept of time..
        /// </summary>
        internal static string Factor_EventorKey {
            get {
                return ResourceManager.GetString("Factor_EventorKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifies the type of information and/or level of confidence..
        /// </summary>
        internal static string Factor_FactorAssertionKey {
            get {
                return ResourceManager.GetString("Factor_FactorAssertionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifies the Identor Element, which applies a name or identifier..
        /// </summary>
        internal static string Factor_IdentorKey {
            get {
                return ResourceManager.GetString("Factor_IdentorKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies whether this !Factor helps to uniquely define the primary Artifact..
        /// </summary>
        internal static string Factor_IsDefining {
            get {
                return ResourceManager.GetString("Factor_IsDefining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the level of access..
        /// </summary>
        internal static string Factor_IsPublic {
            get {
                return ResourceManager.GetString("Factor_IsPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifies the Locator Element, which provides a geographical or relative position..
        /// </summary>
        internal static string Factor_LocatorKey {
            get {
                return ResourceManager.GetString("Factor_LocatorKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A summary of the !Factor&apos;s intended meaning or purpose. This is useful in cases when the !Factor is vague, complex, or confusing. It can help resolve issues in cases where the Factor&apos;s Elements inaccurately model the intended meaning. Typically, this value is not written directly by a User; the App should have enough information about a particular !Factor-creating action to form a reasonable sentence or phrase. Maximum length: 256 characters..
        /// </summary>
        internal static string Factor_Note {
            get {
                return ResourceManager.GetString("Factor_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifies the primary (first) part of the directional Artifact relationship..
        /// </summary>
        internal static string Factor_PrimaryArtifactKey {
            get {
                return ResourceManager.GetString("Factor_PrimaryArtifactKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifies the related (second) part of the directional Artifact relationship..
        /// </summary>
        internal static string Factor_RelatedArtifactKey {
            get {
                return ResourceManager.GetString("Factor_RelatedArtifactKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifies the Vector Element, which applies a numeric axis and value..
        /// </summary>
        internal static string Factor_VectorKey {
            get {
                return ResourceManager.GetString("Factor_VectorKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information about the details and/or causes of the Fault..
        /// </summary>
        internal static string Fault_Message {
            get {
                return ResourceManager.GetString("Fault_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifies the value&apos;s purpose or intent..
        /// </summary>
        internal static string Identor_IdentorTypeKey {
            get {
                return ResourceManager.GetString("Identor_IdentorTypeKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A text-based value that can represent names, numbers, IDs, GUIDs, etc. Maximum length: 256 characters..
        /// </summary>
        internal static string Identor_Value {
            get {
                return ResourceManager.GetString("Identor_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifies a particular object..
        /// </summary>
        internal static string Key_Id {
            get {
                return ResourceManager.GetString("Key_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The API request path to get information about this Key&apos;s object..
        /// </summary>
        internal static string Key_Uri {
            get {
                return ResourceManager.GetString("Key_Uri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A unique title or identifier. Maximum length: 128 characters. This string is restricted to the [[Title character set|Note|TitleCharSet]]..
        /// </summary>
        internal static string Label_Name {
            get {
                return ResourceManager.GetString("Label_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifies the spatial context of the coordinate..
        /// </summary>
        internal static string Locator_LocatorTypeKey {
            get {
                return ResourceManager.GetString("Locator_LocatorTypeKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A value representing longitude, time/progress, width, or a particular three-dimensional axis..
        /// </summary>
        internal static string Locator_ValueX {
            get {
                return ResourceManager.GetString("Locator_ValueX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A value representing latitude, height, or a particular three-dimensional axis..
        /// </summary>
        internal static string Locator_ValueY {
            get {
                return ResourceManager.GetString("Locator_ValueY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A value representing elevation or a particular three-dimensional axis..
        /// </summary>
        internal static string Locator_ValueZ {
            get {
                return ResourceManager.GetString("Locator_ValueZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum Locator X-coordinate value..
        /// </summary>
        internal static string LocatorType_MaxX {
            get {
                return ResourceManager.GetString("LocatorType_MaxX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum Locator Y-coordinate value..
        /// </summary>
        internal static string LocatorType_MaxY {
            get {
                return ResourceManager.GetString("LocatorType_MaxY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum Locator Z-coordinate value..
        /// </summary>
        internal static string LocatorType_MaxZ {
            get {
                return ResourceManager.GetString("LocatorType_MaxZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum Locator X-coordinate value..
        /// </summary>
        internal static string LocatorType_MinX {
            get {
                return ResourceManager.GetString("LocatorType_MinX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum Locator Y-coordinate value..
        /// </summary>
        internal static string LocatorType_MinY {
            get {
                return ResourceManager.GetString("LocatorType_MinY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum Locator Z-coordinate value..
        /// </summary>
        internal static string LocatorType_MinZ {
            get {
                return ResourceManager.GetString("LocatorType_MinZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifies the membership state and/or access privileges..
        /// </summary>
        internal static string Member_MemberTypeKey {
            get {
                return ResourceManager.GetString("Member_MemberTypeKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        internal static string Node_NodeId {
            get {
                return ResourceManager.GetString("Node_NodeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        internal static string Node_NodeUri {
            get {
                return ResourceManager.GetString("Node_NodeUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        internal static string NodeForAction_Note {
            get {
                return ResourceManager.GetString("NodeForAction_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        internal static string NodeForAction_Performed {
            get {
                return ResourceManager.GetString("NodeForAction_Performed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        internal static string NodeForType_Description {
            get {
                return ResourceManager.GetString("NodeForType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        internal static string NodeForType_Name {
            get {
                return ResourceManager.GetString("NodeForType_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uniquely identifies this object amongst all other objects of this type..
        /// </summary>
        internal static string Object_TypeId {
            get {
                return ResourceManager.GetString("Object_TypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        internal static string Response_AvailableUris {
            get {
                return ResourceManager.GetString("Response_AvailableUris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        internal static string Response_BaseUri {
            get {
                return ResourceManager.GetString("Response_BaseUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        internal static string Response_Count {
            get {
                return ResourceManager.GetString("Response_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        internal static string Response_Data {
            get {
                return ResourceManager.GetString("Response_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        internal static string Response_DataLen {
            get {
                return ResourceManager.GetString("Response_DataLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        internal static string Response_DbMs {
            get {
                return ResourceManager.GetString("Response_DbMs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        internal static string Response_HasMore {
            get {
                return ResourceManager.GetString("Response_HasMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        internal static string Response_RequestUri {
            get {
                return ResourceManager.GetString("Response_RequestUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        internal static string Response_StartIndex {
            get {
                return ResourceManager.GetString("Response_StartIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        internal static string Response_Timestamp {
            get {
                return ResourceManager.GetString("Response_Timestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        internal static string Response_TotalMs {
            get {
                return ResourceManager.GetString("Response_TotalMs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        internal static string Response_Type {
            get {
                return ResourceManager.GetString("Response_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A secondary label or identifier, used to resolve unique-name conflicts. Maximum length: 128 characters..
        /// </summary>
        internal static string Thing_Disamb {
            get {
                return ResourceManager.GetString("Thing_Disamb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the type: Class or Instance..
        /// </summary>
        internal static string Thing_IsClass {
            get {
                return ResourceManager.GetString("Thing_IsClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A descriptive name or title..
        /// </summary>
        internal static string Thing_Name {
            get {
                return ResourceManager.GetString("Thing_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A summary of the !Thing&apos;s intended meaning or purpose. This can resolve confusion in cases where a !Thing has vague or missing Factors.  Maximum length: 256 characters..
        /// </summary>
        internal static string Thing_Note {
            get {
                return ResourceManager.GetString("Thing_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        internal static string TODO {
            get {
                return ResourceManager.GetString("TODO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A unique, valid absolute URL. The string must include the link&apos;s protocol (such as &apos;http://&apos;). Maximum length: 450 characters..
        /// </summary>
        internal static string Url_AbsoluteUrl {
            get {
                return ResourceManager.GetString("Url_AbsoluteUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A descriptive name or title..
        /// </summary>
        internal static string Url_Name {
            get {
                return ResourceManager.GetString("Url_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A unique username, with length between 4 and 16 characters. This string is restricted to the [[Username character set|Note|UsernameCharSet]]..
        /// </summary>
        internal static string User_Name {
            get {
                return ResourceManager.GetString("User_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifies the value&apos;s axis using an arbitrary Artifact..
        /// </summary>
        internal static string Vector_AxisArtifactKey {
            get {
                return ResourceManager.GetString("Vector_AxisArtifactKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An integral value which is to be plotted along the specified axis. This value must account for the choice of prefix. After being multiplied by the prefix magnitude, the value must fall within the bounds specified by VectorType. Before prefix multiplication, this value must be between –9,223,372,036,854,775,808 and 9,223,372,036,854,775,807..
        /// </summary>
        internal static string Vector_Value {
            get {
                return ResourceManager.GetString("Vector_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifies the value&apos;s boundaries and context..
        /// </summary>
        internal static string Vector_VectorTypeKey {
            get {
                return ResourceManager.GetString("Vector_VectorTypeKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifies the value&apos;s unit of measurement..
        /// </summary>
        internal static string Vector_VectorUnitKey {
            get {
                return ResourceManager.GetString("Vector_VectorUnitKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifies the value&apos;s order of magnitude..
        /// </summary>
        internal static string Vector_VectorUnitPrefixKey {
            get {
                return ResourceManager.GetString("Vector_VectorUnitPrefixKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The set of points/labels that describe a numerical range..
        /// </summary>
        internal static string VectorRange_Levels {
            get {
                return ResourceManager.GetString("VectorRange_Levels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A value (between 0.0 and 1.0) which defines the relative position between a numeric range&apos;s minimum and maximum boundaries..
        /// </summary>
        internal static string VectorRangeLevel_Position {
            get {
                return ResourceManager.GetString("VectorRangeLevel_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifies the parent VectorRange..
        /// </summary>
        internal static string VectorRangeLevel_RangeKey {
            get {
                return ResourceManager.GetString("VectorRangeLevel_RangeKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum Vector value allowed..
        /// </summary>
        internal static string VectorType_Max {
            get {
                return ResourceManager.GetString("VectorType_Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum Vector value allowed..
        /// </summary>
        internal static string VectorType_Min {
            get {
                return ResourceManager.GetString("VectorType_Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifies a set of meaningful points/labels which map to the numerical range..
        /// </summary>
        internal static string VectorType_RangeKey {
            get {
                return ResourceManager.GetString("VectorType_RangeKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A unique symbol or abbreviation. Maximum length: 16 characters..
        /// </summary>
        internal static string VectorUnit_Symbol {
            get {
                return ResourceManager.GetString("VectorUnit_Symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        internal static string VectorUnitDerived_Exponent {
            get {
                return ResourceManager.GetString("VectorUnitDerived_Exponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The difference in magnitude (a multipler) relative to the base unit..
        /// </summary>
        internal static string VectorUnitPrefix_Amount {
            get {
                return ResourceManager.GetString("VectorUnitPrefix_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An abbreviation, which is typically placed directly before the VectorUnit symbol.  Maximum length: 2 characters..
        /// </summary>
        internal static string VectorUnitPrefix_Symbol {
            get {
                return ResourceManager.GetString("VectorUnitPrefix_Symbol", resourceCulture);
            }
        }
    }
}
