//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fabric.Api.Content {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WebResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fabric.Api.Content.WebResources", typeof(WebResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;meta charset=&quot;utf-8&quot; /&gt;
        ///		&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot; /&gt;
        ///		&lt;title&gt;@TITLE&lt;/title&gt;
        ///		&lt;link href=&quot;/Content/favicon.ico&quot; rel=&quot;shortcut icon&quot; type=&quot;image/x-icon&quot; /&gt;
        ///		&lt;link rel=&apos;stylesheet&apos; type=&apos;text/css&apos; href=&apos;/Content/Foundation.css&apos;&gt;
        ///		&lt;link rel=&apos;stylesheet&apos; type=&apos;text/css&apos; href=&apos;/Content/Site.css&apos;&gt;
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///		&lt;div id=&quot;HeaderSpacer&quot; class=&quot;hide-for-small&quot;&gt;&lt;/div&gt;
        ///
        ///		&lt;header id=&quot;Header&quot; class=&quot;row&quot;&gt;
        ///			&lt;div id=&quot;HeaderTopLine&quot;&gt;&lt;/div&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LayoutHtml {
            get {
                return ResourceManager.GetString("LayoutHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;row&quot;&gt;
        ///	&lt;div class=&quot;twelve columns&quot;&gt;
        ///		&lt;p&gt;
        ///			&lt;b&gt;@ErrorName&lt;/b&gt;&lt;br/&gt;
        ///			@ErrorDesc
        ///		&lt;/p&gt;
        ///	&lt;/div&gt;
        ///&lt;/div&gt;.
        /// </summary>
        public static string LoginErrorHtml {
            get {
                return ResourceManager.GetString("LoginErrorHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;row&quot;&gt;
        ///	&lt;div class=&quot;twelve columns&quot;&gt;
        ///		&lt;p&gt;
        ///			&lt;b&gt;@AppName&lt;/b&gt; would like to connect to your Fabric account. Please log in to continue.
        ///		&lt;/p&gt;
        ///	&lt;/div&gt;
        ///&lt;/div&gt;
        ///
        ///&lt;div class=&quot;row&quot;&gt;
        ///	&lt;div class=&quot;twelve columns&quot;&gt;
        ///		&lt;form id=&quot;LoginForm&quot; action=&quot;&quot; method=&quot;POST&quot;&gt;
        ///			&lt;fieldset class=&quot;calloutBox&quot;&gt;
        ///				&lt;div class=&quot;validation-summary-errors&quot; style=&quot;margin-top:5px; display: @ErrorDisplayStyle&quot;&gt;
        ///					&lt;span&gt;Oops! Here&amp;#39;s why your login failed:&lt;/span&gt;
        ///					&lt;ul&gt;
        ///						&lt;li&gt;@ErrorReason&lt;/li&gt;
        ///					&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LoginPageHtml {
            get {
                return ResourceManager.GetString("LoginPageHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;row&quot;&gt;
        ///	&lt;div class=&quot;twelve columns&quot;&gt;
        ///		&lt;p&gt;Hello! You are logged in as &lt;b&gt;@LoggedUserName&lt;/b&gt;. Please choose an option below.&lt;/p&gt;
        ///	&lt;/div&gt;
        ///&lt;/div&gt;
        ///
        ///&lt;div class=&quot;row&quot;&gt;
        ///	&lt;div class=&quot;twelve columns&quot;&gt;
        ///		
        ///		&lt;form id=&quot;ScopeForm&quot; action=&quot;&quot; method=&quot;POST&quot;&gt;
        ///			&lt;fieldset class=&quot;calloutBox&quot;&gt;
        ///				&lt;p&gt;Will you allow &lt;b&gt;@AppName&lt;/b&gt; to connect to your Fabric account?&lt;/p&gt;
        ///				&lt;input type=&quot;submit&quot; name=&quot;@AllowAction&quot; value=&quot;Allow&quot; class=&quot;formButton&quot; /&gt;
        ///				&lt;input type=&quot;submit&quot; name=&quot;@DenyAction&quot; value=&quot;De [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LoginScopeHtml {
            get {
                return ResourceManager.GetString("LoginScopeHtml", resourceCulture);
            }
        }
    }
}
